/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type LogAnalyticsEntityAssociationsAddInitParameters struct {

	// Destination entities OCIDs with which associations are to be added.
	AssociationEntities []*string `json:"associationEntities,omitempty" tf:"association_entities,omitempty"`

	// The Log analytics entity OCID.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/loganalytics/v1alpha1.LogAnalyticsEntity
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	LogAnalyticsEntityID *string `json:"logAnalyticsEntityId,omitempty" tf:"log_analytics_entity_id,omitempty"`

	// Reference to a LogAnalyticsEntity in loganalytics to populate logAnalyticsEntityId.
	// +kubebuilder:validation:Optional
	LogAnalyticsEntityIDRef *v1.Reference `json:"logAnalyticsEntityIdRef,omitempty" tf:"-"`

	// Selector for a LogAnalyticsEntity in loganalytics to populate logAnalyticsEntityId.
	// +kubebuilder:validation:Optional
	LogAnalyticsEntityIDSelector *v1.Selector `json:"logAnalyticsEntityIdSelector,omitempty" tf:"-"`

	// The Log Analytics namespace used for the request.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type LogAnalyticsEntityAssociationsAddObservation struct {

	// Destination entities OCIDs with which associations are to be added.
	AssociationEntities []*string `json:"associationEntities,omitempty" tf:"association_entities,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The Log analytics entity OCID.
	LogAnalyticsEntityID *string `json:"logAnalyticsEntityId,omitempty" tf:"log_analytics_entity_id,omitempty"`

	// The Log Analytics namespace used for the request.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

type LogAnalyticsEntityAssociationsAddParameters struct {

	// Destination entities OCIDs with which associations are to be added.
	// +kubebuilder:validation:Optional
	AssociationEntities []*string `json:"associationEntities,omitempty" tf:"association_entities,omitempty"`

	// The Log analytics entity OCID.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/loganalytics/v1alpha1.LogAnalyticsEntity
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	LogAnalyticsEntityID *string `json:"logAnalyticsEntityId,omitempty" tf:"log_analytics_entity_id,omitempty"`

	// Reference to a LogAnalyticsEntity in loganalytics to populate logAnalyticsEntityId.
	// +kubebuilder:validation:Optional
	LogAnalyticsEntityIDRef *v1.Reference `json:"logAnalyticsEntityIdRef,omitempty" tf:"-"`

	// Selector for a LogAnalyticsEntity in loganalytics to populate logAnalyticsEntityId.
	// +kubebuilder:validation:Optional
	LogAnalyticsEntityIDSelector *v1.Selector `json:"logAnalyticsEntityIdSelector,omitempty" tf:"-"`

	// The Log Analytics namespace used for the request.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`
}

// LogAnalyticsEntityAssociationsAddSpec defines the desired state of LogAnalyticsEntityAssociationsAdd
type LogAnalyticsEntityAssociationsAddSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     LogAnalyticsEntityAssociationsAddParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider LogAnalyticsEntityAssociationsAddInitParameters `json:"initProvider,omitempty"`
}

// LogAnalyticsEntityAssociationsAddStatus defines the observed state of LogAnalyticsEntityAssociationsAdd.
type LogAnalyticsEntityAssociationsAddStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        LogAnalyticsEntityAssociationsAddObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// LogAnalyticsEntityAssociationsAdd is the Schema for the LogAnalyticsEntityAssociationsAdds API. Provides the Log Analytics Entity Associations Add resource in Oracle Cloud Infrastructure Log Analytics service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type LogAnalyticsEntityAssociationsAdd struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.associationEntities) || (has(self.initProvider) && has(self.initProvider.associationEntities))",message="spec.forProvider.associationEntities is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.__namespace__) || (has(self.initProvider) && has(self.initProvider.__namespace__))",message="spec.forProvider.namespace is a required parameter"
	Spec   LogAnalyticsEntityAssociationsAddSpec   `json:"spec"`
	Status LogAnalyticsEntityAssociationsAddStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// LogAnalyticsEntityAssociationsAddList contains a list of LogAnalyticsEntityAssociationsAdds
type LogAnalyticsEntityAssociationsAddList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []LogAnalyticsEntityAssociationsAdd `json:"items"`
}

// Repository type metadata.
var (
	LogAnalyticsEntityAssociationsAdd_Kind             = "LogAnalyticsEntityAssociationsAdd"
	LogAnalyticsEntityAssociationsAdd_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: LogAnalyticsEntityAssociationsAdd_Kind}.String()
	LogAnalyticsEntityAssociationsAdd_KindAPIVersion   = LogAnalyticsEntityAssociationsAdd_Kind + "." + CRDGroupVersion.String()
	LogAnalyticsEntityAssociationsAdd_GroupVersionKind = CRDGroupVersion.WithKind(LogAnalyticsEntityAssociationsAdd_Kind)
)

func init() {
	SchemeBuilder.Register(&LogAnalyticsEntityAssociationsAdd{}, &LogAnalyticsEntityAssociationsAddList{})
}
