/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AutoScalingConfiguration.
func (mg *AutoScalingConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Policies); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.Policies[i3].Rules); i4++ {
			for i5 := 0; i5 < len(mg.Spec.ForProvider.Policies[i3].Rules[i4].Metric); i5++ {
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.ForProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentIDRef,
					Selector:     mg.Spec.ForProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentIDSelector,
					To: reference.To{
						List:    &v1alpha1.CompartmentList{},
						Managed: &v1alpha1.Compartment{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.ForProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentID")
				}
				mg.Spec.ForProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.ForProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentIDRef = rsp.ResolvedReference

			}
		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Policies); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.Policies[i3].Rules); i4++ {
			for i5 := 0; i5 < len(mg.Spec.InitProvider.Policies[i3].Rules[i4].Metric); i5++ {
				rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
					CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentID),
					Extract:      resource.ExtractResourceID(),
					Namespace:    mg.GetNamespace(),
					Reference:    mg.Spec.InitProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentIDRef,
					Selector:     mg.Spec.InitProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentIDSelector,
					To: reference.To{
						List:    &v1alpha1.CompartmentList{},
						Managed: &v1alpha1.Compartment{},
					},
				})
				if err != nil {
					return errors.Wrap(err, "mg.Spec.InitProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentID")
				}
				mg.Spec.InitProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
				mg.Spec.InitProvider.Policies[i3].Rules[i4].Metric[i5].MetricCompartmentIDRef = rsp.ResolvedReference

			}
		}
	}

	return nil
}
