---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: BootVolumeBackup
metadata:
  labels:
    testing.upbound.io/example-name: bootvolumebackup_label_1
  name: bootvolumebackup1
  namespace: crossplane-system
spec:
  forProvider:
    bootVolumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: bootvolume_label_1
    displayName: bootvolumebackup1
    type: FULL
