---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: BootVolume
metadata:
  labels:
    testing.upbound.io/example-name: bootvolume_label_1
  name: bootvolume1
  namespace: crossplane-system
spec:
  forProvider:
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: bootvolume1
    sourceDetails:
    - id: ${BOOT_VOLUME_SOURCE_ID}
      type: bootVolume
