---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: VolumeBackupPolicy
metadata:
  labels:
    testing.upbound.io/example-name: volumebackuppolicy_label_1
  name: volumebackuppolicy1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: volumebackuppolicy1
    schedules:
    - backupType: INCREMENTAL
      period: ONE_DAY
      retentionSeconds: 604800
