---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: Volume
metadata:
  labels:
    testing.upbound.io/example-name: volume_label_1
  name: volume1
  namespace: crossplane-system
spec:
  forProvider:
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: volume1
