---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: VolumeGroup
metadata:
  labels:
    testing.upbound.io/example-name: volumegroup_label_1
  name: volumegroup1
  namespace: crossplane-system
spec:
  forProvider:
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: volumegroup1
    sourceDetails:
    - type: volumeIds
      volumeIdsSelector:
        matchLabels:
          testing.upbound.io/example-name: volume_label_1
