---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: VolumeAttachment
metadata:
  labels:
    testing.upbound.io/example-name: volumeattachment_label_1
  name: volumeattachment1
  namespace: crossplane-system
spec:
  forProvider:
    attachmentType: iscsi
    displayName: volumeattachment1
    instanceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: instance_label_1
    volumeIdSelector:
      matchLabels:
        testing.upbound.io/example-name: volume_label_1
