---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: VolumeGroupBackup
metadata:
  labels:
    testing.upbound.io/example-name: volumegroupbackup_label_1
  name: volumegroupbackup1
  namespace: crossplane-system
spec:
  forProvider:
    displayName: volumegroupbackup1
    type: FULL
    volumeGroupIdSelector:
      matchLabels:
        testing.upbound.io/example-name: volumegroup_label_1
