---
apiVersion: blockstorage.oci.m.upbound.io/v1alpha1
kind: VolumeBackupPolicyAssignment
metadata:
  labels:
    testing.upbound.io/example-name: volumebackuppolicyassignment_label_1
  name: volumebackuppolicyassignment1
  namespace: crossplane-system
spec:
  forProvider:
    assetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: volume_label_1
    policyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: volumebackuppolicy_label_1
