/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type DataSourceInitParameters struct {

	// (Applicable when source_type=HUGGING_FACE_MODEL) Hugging Face access token to authenticate requests for restricted models.  This token will be securely stored in Oracle Cloud Infrastructure Vault.
	AccessToken *string `json:"accessToken,omitempty" tf:"access_token,omitempty"`

	// (Applicable when source_type=HUGGING_FACE_MODEL) The name of the branch in the Hugging Face repository to import the model from.  If not specified, "main" will be used by default.  If you provide both a branch and a commit hash, the model will be imported from the specified commit.
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The name of the Object Storage bucket.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Applicable when source_type=HUGGING_FACE_MODEL) The commit hash in the Hugging Face repository to import the model from.  If both a branch and a commit are provided, the commit hash will be used.
	Commit *string `json:"commit,omitempty" tf:"commit,omitempty"`

	// The full model OCID from Hugging Face, typically in the format "org/model-name" (e.g., "meta-llama/Llama-2-7b").
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`

	// The namespace of the Object Storage where the files are stored.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The prefix path (or folder) within the bucket where files are located.
	PrefixName *string `json:"prefixName,omitempty" tf:"prefix_name,omitempty"`

	// (Applicable when source_type=OBJECT_STORAGE_OBJECT) The full canonical Oracle Cloud region identifier (e.g., "us-ashburn-1") where the object storage bucket  containing the files resides.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the source type for model import.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type DataSourceObservation struct {

	// (Applicable when source_type=HUGGING_FACE_MODEL) Hugging Face access token to authenticate requests for restricted models.  This token will be securely stored in Oracle Cloud Infrastructure Vault.
	AccessToken *string `json:"accessToken,omitempty" tf:"access_token,omitempty"`

	// (Applicable when source_type=HUGGING_FACE_MODEL) The name of the branch in the Hugging Face repository to import the model from.  If not specified, "main" will be used by default.  If you provide both a branch and a commit hash, the model will be imported from the specified commit.
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The name of the Object Storage bucket.
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Applicable when source_type=HUGGING_FACE_MODEL) The commit hash in the Hugging Face repository to import the model from.  If both a branch and a commit are provided, the commit hash will be used.
	Commit *string `json:"commit,omitempty" tf:"commit,omitempty"`

	// The full model OCID from Hugging Face, typically in the format "org/model-name" (e.g., "meta-llama/Llama-2-7b").
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// The namespace of the Object Storage where the files are stored.
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The prefix path (or folder) within the bucket where files are located.
	PrefixName *string `json:"prefixName,omitempty" tf:"prefix_name,omitempty"`

	// (Applicable when source_type=OBJECT_STORAGE_OBJECT) The full canonical Oracle Cloud region identifier (e.g., "us-ashburn-1") where the object storage bucket  containing the files resides.
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the source type for model import.
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type DataSourceParameters struct {

	// (Applicable when source_type=HUGGING_FACE_MODEL) Hugging Face access token to authenticate requests for restricted models.  This token will be securely stored in Oracle Cloud Infrastructure Vault.
	// +kubebuilder:validation:Optional
	AccessToken *string `json:"accessToken,omitempty" tf:"access_token,omitempty"`

	// (Applicable when source_type=HUGGING_FACE_MODEL) The name of the branch in the Hugging Face repository to import the model from.  If not specified, "main" will be used by default.  If you provide both a branch and a commit hash, the model will be imported from the specified commit.
	// +kubebuilder:validation:Optional
	Branch *string `json:"branch,omitempty" tf:"branch,omitempty"`

	// The name of the Object Storage bucket.
	// +kubebuilder:validation:Optional
	Bucket *string `json:"bucket,omitempty" tf:"bucket,omitempty"`

	// (Applicable when source_type=HUGGING_FACE_MODEL) The commit hash in the Hugging Face repository to import the model from.  If both a branch and a commit are provided, the commit hash will be used.
	// +kubebuilder:validation:Optional
	Commit *string `json:"commit,omitempty" tf:"commit,omitempty"`

	// The full model OCID from Hugging Face, typically in the format "org/model-name" (e.g., "meta-llama/Llama-2-7b").
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/generativeai/v1alpha1.Model
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	ModelID *string `json:"modelId,omitempty" tf:"model_id,omitempty"`

	// Reference to a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDRef *v1.Reference `json:"modelIdRef,omitempty" tf:"-"`

	// Selector for a Model in generativeai to populate modelId.
	// +kubebuilder:validation:Optional
	ModelIDSelector *v1.Selector `json:"modelIdSelector,omitempty" tf:"-"`

	// The namespace of the Object Storage where the files are stored.
	// +kubebuilder:validation:Optional
	Namespace *string `json:"namespace,omitempty" tf:"namespace,omitempty"`

	// The prefix path (or folder) within the bucket where files are located.
	// +kubebuilder:validation:Optional
	PrefixName *string `json:"prefixName,omitempty" tf:"prefix_name,omitempty"`

	// (Applicable when source_type=OBJECT_STORAGE_OBJECT) The full canonical Oracle Cloud region identifier (e.g., "us-ashburn-1") where the object storage bucket  containing the files resides.
	// +kubebuilder:validation:Optional
	Region *string `json:"region,omitempty" tf:"region,omitempty"`

	// Specifies the source type for model import.
	// +kubebuilder:validation:Optional
	SourceType *string `json:"sourceType,omitempty" tf:"source_type,omitempty"`
}

type ImportedModelInitParameters struct {

	// Specifies the intended use or supported capabilities of the imported model.
	Capabilities []*string `json:"capabilities,omitempty" tf:"capabilities,omitempty"`

	// (Updatable) The compartment OCID from which the model is imported.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// Defines the source location and method used to import the model. Supports importing from Hugging Face,  an Object Storage location, or by referencing an already imported model.
	DataSource []DataSourceInitParameters `json:"dataSource,omitempty" tf:"data_source,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the imported model.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name for the imported model.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The provider of the imported model.
	Vendor *string `json:"vendor,omitempty" tf:"vendor,omitempty"`

	// (Updatable) The version of the imported model.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ImportedModelObservation struct {

	// Specifies the intended use or supported capabilities of the imported model.
	Capabilities []*string `json:"capabilities,omitempty" tf:"capabilities,omitempty"`

	// (Updatable) The compartment OCID from which the model is imported.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Defines the source location and method used to import the model. Supports importing from Hugging Face,  an Object Storage location, or by referencing an already imported model.
	DataSource []DataSourceObservation `json:"dataSource,omitempty" tf:"data_source,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the imported model.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name for the imported model.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// An OCID that uniquely identifies an imported model.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Additional information about the current state of the imported model, providing more detailed and actionable context.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Represents a model imported into the system based on an external data source, such as Hugging Face or Object Storage.
	PreviousState *string `json:"previousState,omitempty" tf:"previous_state,omitempty"`

	// The lifecycle state of the imported model.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time that the imported model was created in the format of an RFC3339 datetime string.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time that the imported model was updated in the format of an RFC3339 datetime string.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// (Updatable) The provider of the imported model.
	Vendor *string `json:"vendor,omitempty" tf:"vendor,omitempty"`

	// (Updatable) The version of the imported model.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ImportedModelParameters struct {

	// Specifies the intended use or supported capabilities of the imported model.
	// +kubebuilder:validation:Optional
	Capabilities []*string `json:"capabilities,omitempty" tf:"capabilities,omitempty"`

	// (Updatable) The compartment OCID from which the model is imported.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// Defines the source location and method used to import the model. Supports importing from Hugging Face,  an Object Storage location, or by referencing an already imported model.
	// +kubebuilder:validation:Optional
	DataSource []DataSourceParameters `json:"dataSource,omitempty" tf:"data_source,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) An optional description of the imported model.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name for the imported model.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The provider of the imported model.
	// +kubebuilder:validation:Optional
	Vendor *string `json:"vendor,omitempty" tf:"vendor,omitempty"`

	// (Updatable) The version of the imported model.
	// +kubebuilder:validation:Optional
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

// ImportedModelSpec defines the desired state of ImportedModel
type ImportedModelSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ImportedModelParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ImportedModelInitParameters `json:"initProvider,omitempty"`
}

// ImportedModelStatus defines the observed state of ImportedModel.
type ImportedModelStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ImportedModelObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ImportedModel is the Schema for the ImportedModels API. Provides the Imported Model resource in Oracle Cloud Infrastructure Generative AI service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ImportedModel struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.dataSource) || (has(self.initProvider) && has(self.initProvider.dataSource))",message="spec.forProvider.dataSource is a required parameter"
	Spec   ImportedModelSpec   `json:"spec"`
	Status ImportedModelStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ImportedModelList contains a list of ImportedModels
type ImportedModelList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ImportedModel `json:"items"`
}

// Repository type metadata.
var (
	ImportedModel_Kind             = "ImportedModel"
	ImportedModel_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ImportedModel_Kind}.String()
	ImportedModel_KindAPIVersion   = ImportedModel_Kind + "." + CRDGroupVersion.String()
	ImportedModel_GroupVersionKind = CRDGroupVersion.WithKind(ImportedModel_Kind)
)

func init() {
	SchemeBuilder.Register(&ImportedModel{}, &ImportedModelList{})
}
