/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AlertRule.
func (mg *AlertRule) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BudgetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BudgetIDRef,
		Selector:     mg.Spec.ForProvider.BudgetIDSelector,
		To: reference.To{
			List:    &BudgetList{},
			Managed: &Budget{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BudgetID")
	}
	mg.Spec.ForProvider.BudgetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BudgetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BudgetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BudgetIDRef,
		Selector:     mg.Spec.InitProvider.BudgetIDSelector,
		To: reference.To{
			List:    &BudgetList{},
			Managed: &Budget{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BudgetID")
	}
	mg.Spec.InitProvider.BudgetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BudgetIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Budget.
func (mg *Budget) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TargetCompartmentID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.TargetCompartmentIDRef,
		Selector:     mg.Spec.ForProvider.TargetCompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.TargetCompartmentID")
	}
	mg.Spec.ForProvider.TargetCompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.TargetCompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TargetCompartmentID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.TargetCompartmentIDRef,
		Selector:     mg.Spec.InitProvider.TargetCompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.TargetCompartmentID")
	}
	mg.Spec.InitProvider.TargetCompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.TargetCompartmentIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this CostAlertSubscription.
func (mg *CostAlertSubscription) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this CostAnomalyEvent.
func (mg *CostAnomalyEvent) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CostAnomalyEventID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CostAnomalyEventIDRef,
		Selector:     mg.Spec.ForProvider.CostAnomalyEventIDSelector,
		To: reference.To{
			List:    &CostAnomalyEventList{},
			Managed: &CostAnomalyEvent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CostAnomalyEventID")
	}
	mg.Spec.ForProvider.CostAnomalyEventID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CostAnomalyEventIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CostAnomalyEventID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CostAnomalyEventIDRef,
		Selector:     mg.Spec.InitProvider.CostAnomalyEventIDSelector,
		To: reference.To{
			List:    &CostAnomalyEventList{},
			Managed: &CostAnomalyEvent{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CostAnomalyEventID")
	}
	mg.Spec.InitProvider.CostAnomalyEventID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CostAnomalyEventIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this CostAnomalyMonitor.
func (mg *CostAnomalyMonitor) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.CostAlertSubscriptionMap); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionIDRef,
			Selector:     mg.Spec.ForProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionIDSelector,
			To: reference.To{
				List:    &CostAlertSubscriptionList{},
				Managed: &CostAlertSubscription{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionID")
		}
		mg.Spec.ForProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.CostAlertSubscriptionMap); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionIDRef,
			Selector:     mg.Spec.InitProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionIDSelector,
			To: reference.To{
				List:    &CostAlertSubscriptionList{},
				Managed: &CostAlertSubscription{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionID")
		}
		mg.Spec.InitProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CostAlertSubscriptionMap[i3].CostAlertSubscriptionIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this CostAnomalyMonitorCostanomalymonitorenabletogglesManagement.
func (mg *CostAnomalyMonitorCostanomalymonitorenabletogglesManagement) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CostAnomalyMonitorID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CostAnomalyMonitorIDRef,
		Selector:     mg.Spec.ForProvider.CostAnomalyMonitorIDSelector,
		To: reference.To{
			List:    &CostAnomalyMonitorList{},
			Managed: &CostAnomalyMonitor{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CostAnomalyMonitorID")
	}
	mg.Spec.ForProvider.CostAnomalyMonitorID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CostAnomalyMonitorIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CostAnomalyMonitorID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CostAnomalyMonitorIDRef,
		Selector:     mg.Spec.InitProvider.CostAnomalyMonitorIDSelector,
		To: reference.To{
			List:    &CostAnomalyMonitorList{},
			Managed: &CostAnomalyMonitor{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CostAnomalyMonitorID")
	}
	mg.Spec.InitProvider.CostAnomalyMonitorID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CostAnomalyMonitorIDRef = rsp.ResolvedReference

	return nil
}
