---
apiVersion: redis.oci.m.upbound.io/v1alpha1
kind: OciCacheConfigSet
metadata:
  labels:
    testing.upbound.io/example-name: ocicacheconfigset_label_1
  name: ocicacheconfigset1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    configurationDetails:
    - items:
      - configKey: timeout
        configValue: '0'
    displayName: ocicacheconfigset1
    softwareVersion: REDIS_7_0
