---
apiVersion: redis.oci.m.upbound.io/v1alpha1
kind: OciCacheUser
metadata:
  labels:
    testing.upbound.io/example-name: ocicacheuser_label_1
  name: ocicacheuser1
  namespace: crossplane-system
spec:
  forProvider:
    aclString: ~* +get +set
    authenticationMode:
    - authenticationType: password
      hashedPasswordsSecretRef:
      - key: password
        name: rediscacheusersecret1
        namespace: default
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    description: cache user for testing
    name: ocicacheuser1
    status: ON
