---
apiVersion: redis.oci.m.upbound.io/v1alpha1
kind: OciCacheUserGetRedisCluster
metadata:
  labels:
    testing.upbound.io/example-name: ocicacheusergetrediscluster_label_1
  name: ocicacheusergetrediscluster1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: ocicacheusergetrediscluster1
    ociCacheUserIdSelector:
      matchLabels:
        testing.upbound.io/example-name: ocicacheuser_label_1
