---
apiVersion: redis.oci.m.upbound.io/v1alpha1
kind: RedisCluster
metadata:
  labels:
    testing.upbound.io/example-name: rediscluster_label_1
  name: rediscluster1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: rediscluster1
    nodeCount: 1
    nodeMemoryInGbs: 2
    softwareVersion: REDIS_7_0
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_label_1
