---
apiVersion: redis.oci.m.upbound.io/v1alpha1
kind: RedisClusterDetachOciCacheUser
metadata:
  labels:
    testing.upbound.io/example-name: redisclusterdetachocicacheuser_label_1
  name: redisclusterdetachocicacheuser1
  namespace: crossplane-system
spec:
  forProvider:
    ociCacheUsersSelector:
      matchLabels:
        testing.upbound.io/example-name: ocicacheuser_label_1
    redisClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: rediscluster_label_1
