---
apiVersion: redis.oci.m.upbound.io/v1alpha1
kind: RedisClusterAttachOciCacheUser
metadata:
  labels:
    testing.upbound.io/example-name: redisclusterattachocicacheuser_label_1
  name: redisclusterattachocicacheuser1
  namespace: crossplane-system
spec:
  forProvider:
    ociCacheUsersSelector:
      matchLabels:
        testing.upbound.io/example-name: ocicacheuser_label_1
    redisClusterIdSelector:
      matchLabels:
        testing.upbound.io/example-name: rediscluster_label_1
