---
apiVersion: compute.oci.m.upbound.io/v1alpha1
kind: InstanceConfiguration
metadata:
  labels:
    testing.upbound.io/example-name: instanceconfiguration_label_2
  name: instanceconfiguration2
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: instanceconfiguration2
    instanceDetails:
    - instanceType: compute
      launchDetails:
      - compartmentId: ${COMPARTMENT_OCID}
        shape: VM.Standard.E4.Flex
        shapeConfig:
        - memoryInGbs: 16
          ocpus: 1
        sourceDetails:
        - imageIdSelector:
            matchLabels:
              testing.upbound.io/example-name: image_label_1
          sourceType: IMAGE
