---
apiVersion: compute.oci.m.upbound.io/v1alpha1
kind: ComputeHost
metadata:
  labels:
    testing.upbound.io/example-name: computehost_label_1
  name: computehost1
  namespace: crossplane-system
spec:
  forProvider:
    computeHostId: ${COMPUTEHOST_ID}
