---
apiVersion: objectstorage.oci.m.upbound.io/v1alpha1
kind: Bucket
metadata:
  labels:
    testing.upbound.io/example-name: bucketwithretnetionrule_label_1
  name: bucketwithretnetionrule1
  namespace: crossplane-system
spec:
  forProvider:
    accessType: NoPublicAccess
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    name: bucketwithretnetionrule1
    namespace: ${OBJECTSTORAGE_NAMESPACE}
    retentionRules:
    - displayName: retentionrule1
      duration:
      - timeAmount: '10'
        timeUnit: DAYS
      timeRuleLocked: 2026-12-12T23:00:00Z
