---
apiVersion: objectstorage.oci.m.upbound.io/v1alpha1
kind: ObjectLifecyclePolicy
metadata:
  labels:
    testing.upbound.io/example-name: objectlifecyclepolicy_label_1
  name: objectlifecyclepolicy1
  namespace: crossplane-system
spec:
  forProvider:
    bucket: bucket1
    namespace: ${OBJECTSTORAGE_NAMESPACE}
    rules:
    - action: ARCHIVE
      isEnabled: true
      name: rule1
      target: objects
      timeAmount: '5'
      timeUnit: DAYS
