---
apiVersion: objectstorage.oci.m.upbound.io/v1alpha1
kind: Object
metadata:
  labels:
    testing.upbound.io/example-name: object_label_1
  name: object1
  namespace: crossplane-system
spec:
  forProvider:
    bucket: bucket1
    content: Hello from Crossplane OCI Object!
    contentDisposition: attachment; filename="hello.txt"
    contentLanguage: en-US
    contentType: text/plain
    namespace: ${OBJECTSTORAGE_NAMESPACE}
    object: object1
    storageTier: InfrequentAccess
