---
apiVersion: objectstorage.oci.m.upbound.io/v1alpha1
kind: Preauthrequest
metadata:
  labels:
    testing.upbound.io/example-name: preauthrequest_label_1
  name: preauthrequest1
  namespace: crossplane-system
spec:
  forProvider:
    accessType: AnyObjectWrite
    bucket: bucket1
    name: preauthrequest1
    namespace: ${OBJECTSTORAGE_NAMESPACE}
    timeExpires: 2026-12-12T23:00:00Z
