---
apiVersion: networkloadbalancer.oci.m.upbound.io/v1alpha1
kind: NetworkLoadBalancersBackendSetsUnified
metadata:
  labels:
    testing.upbound.io/example-name: networkloadbalancersbackedsetsunified_label_1
  name: networkloadbalancersbackedsetsunified1
  namespace: crossplane-system
spec:
  forProvider:
    healthChecker:
    - protocol: TCP
    name: networkloadbalancersbackedsetsunified1
    networkLoadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: networkloadbalancer_label_1
    policy: FIVE_TUPLE
