apiVersion: distributed.oci.m.upbound.io/v1alpha1
kind: DatabaseDistributedDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: distributed/v1alpha1/databasedistributeddatabase
  labels:
    testing.upbound.io/example-name: test_distributed_database
  name: test-distributed-database
  namespace: upbound-system
spec:
  forProvider:
    catalogDetails:
    - adminPasswordSecretRef:
        key: example-key
        name: example-secret
      kmsKeyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key
      kmsKeyVersionIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key_version
      peerDetails:
      - protectionMode: ${var.distributed_database_catalog_details_peer_details_protection_mode}
        transportType: ${var.distributed_database_catalog_details_peer_details_transport_type}
        vmClusterIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_vm_cluster
      peerVmClusterIds: ${var.distributed_database_catalog_details_peer_vm_cluster_ids}
      shardSpace: ${var.distributed_database_catalog_details_shard_space}
      source: ${var.distributed_database_catalog_details_source}
      vaultIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vault
      vmClusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vm_cluster
    characterSet: ${var.distributed_database_character_set}
    chunks: ${var.distributed_database_chunks}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    databaseVersion: ${var.distributed_database_database_version}
    dbBackupConfig:
    - autoBackupWindow: ${var.distributed_database_db_backup_config_auto_backup_window}
      autoFullBackupDay: ${var.distributed_database_db_backup_config_auto_full_backup_day}
      autoFullBackupWindow: ${var.distributed_database_db_backup_config_auto_full_backup_window}
      backupDeletionPolicy: ${var.distributed_database_db_backup_config_backup_deletion_policy}
      backupDestinationDetails:
      - dbrsPolicyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_policy
        id: ${var.distributed_database_db_backup_config_backup_destination_details_id}
        internetProxy: ${var.distributed_database_db_backup_config_backup_destination_details_internet_proxy}
        isRemote: ${var.distributed_database_db_backup_config_backup_destination_details_is_remote}
        isZeroDataLossEnabled: ${var.distributed_database_db_backup_config_backup_destination_details_is_zero_data_loss_enabled}
        remoteRegion: ${var.distributed_database_db_backup_config_backup_destination_details_remote_region}
        type: ${var.distributed_database_db_backup_config_backup_destination_details_type}
        vpcPasswordSecretRef:
          key: example-key
          name: example-secret
        vpcUser: ${var.distributed_database_db_backup_config_backup_destination_details_vpc_user}
      canRunImmediateFullBackup: ${var.distributed_database_db_backup_config_can_run_immediate_full_backup}
      isAutoBackupEnabled: ${var.distributed_database_db_backup_config_is_auto_backup_enabled}
      isRemoteBackupEnabled: ${var.distributed_database_db_backup_config_is_remote_backup_enabled}
      recoveryWindowInDays: ${var.distributed_database_db_backup_config_recovery_window_in_days}
      remoteRegion: ${var.distributed_database_db_backup_config_remote_region}
    dbDeploymentType: ${var.distributed_database_db_deployment_type}
    definedTags:
      foo-namespace.bar-key: value
    displayName: ${var.distributed_database_display_name}
    distributed_database_id: ${var.distributed_database_distributed_database_id}
    freeformTags:
      bar-key: value
    gsmSshPublicKey: ${var.distributed_database_gsm_ssh_public_key}
    listenerPort: ${var.distributed_database_listener_port}
    listenerPortTls: ${var.distributed_database_listener_port_tls}
    ncharacterSet: ${var.distributed_database_ncharacter_set}
    onsPortLocal: ${var.distributed_database_ons_port_local}
    onsPortRemote: ${var.distributed_database_ons_port_remote}
    patchOperations:
    - operation: ${var.distributed_database_patch_operations_operation}
      selection: ${var.distributed_database_patch_operations_selection}
      value: ${var.distributed_database_patch_operations_value}
    prefix: ${var.distributed_database_prefix}
    privateEndpointIds: ${var.distributed_database_private_endpoint_ids}
    replicationFactor: ${var.distributed_database_replication_factor}
    replicationMethod: ${var.distributed_database_replication_method}
    replicationUnit: ${var.distributed_database_replication_unit}
    shardDetails:
    - adminPasswordSecretRef:
        key: example-key
        name: example-secret
      kmsKeyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key
      kmsKeyVersionIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key_version
      peerDetails:
      - protectionMode: ${var.distributed_database_shard_details_peer_details_protection_mode}
        transportType: ${var.distributed_database_shard_details_peer_details_transport_type}
        vmClusterIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_vm_cluster
      peerVmClusterIds: ${var.distributed_database_shard_details_peer_vm_cluster_ids}
      shardSpace: ${var.distributed_database_shard_details_shard_space}
      source: ${var.distributed_database_shard_details_source}
      vaultIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vault
      vmClusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vm_cluster
    shardingMethod: ${var.distributed_database_sharding_method}
