/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type AdvancedClusterFileSystemUnmountInitParameters struct {
	AdvancedClusterFileSystemID *string `json:"advancedClusterFileSystemId,omitempty" tf:"advanced_cluster_file_system_id,omitempty"`
}

type AdvancedClusterFileSystemUnmountObservation struct {
	AdvancedClusterFileSystemID *string `json:"advancedClusterFileSystemId,omitempty" tf:"advanced_cluster_file_system_id,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type AdvancedClusterFileSystemUnmountParameters struct {

	// +kubebuilder:validation:Optional
	AdvancedClusterFileSystemID *string `json:"advancedClusterFileSystemId,omitempty" tf:"advanced_cluster_file_system_id,omitempty"`
}

// AdvancedClusterFileSystemUnmountSpec defines the desired state of AdvancedClusterFileSystemUnmount
type AdvancedClusterFileSystemUnmountSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     AdvancedClusterFileSystemUnmountParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider AdvancedClusterFileSystemUnmountInitParameters `json:"initProvider,omitempty"`
}

// AdvancedClusterFileSystemUnmountStatus defines the observed state of AdvancedClusterFileSystemUnmount.
type AdvancedClusterFileSystemUnmountStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        AdvancedClusterFileSystemUnmountObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// AdvancedClusterFileSystemUnmount is the Schema for the AdvancedClusterFileSystemUnmounts API. <no value>
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type AdvancedClusterFileSystemUnmount struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.advancedClusterFileSystemId) || (has(self.initProvider) && has(self.initProvider.advancedClusterFileSystemId))",message="spec.forProvider.advancedClusterFileSystemId is a required parameter"
	Spec   AdvancedClusterFileSystemUnmountSpec   `json:"spec"`
	Status AdvancedClusterFileSystemUnmountStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// AdvancedClusterFileSystemUnmountList contains a list of AdvancedClusterFileSystemUnmounts
type AdvancedClusterFileSystemUnmountList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []AdvancedClusterFileSystemUnmount `json:"items"`
}

// Repository type metadata.
var (
	AdvancedClusterFileSystemUnmount_Kind             = "AdvancedClusterFileSystemUnmount"
	AdvancedClusterFileSystemUnmount_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: AdvancedClusterFileSystemUnmount_Kind}.String()
	AdvancedClusterFileSystemUnmount_KindAPIVersion   = AdvancedClusterFileSystemUnmount_Kind + "." + CRDGroupVersion.String()
	AdvancedClusterFileSystemUnmount_GroupVersionKind = CRDGroupVersion.WithKind(AdvancedClusterFileSystemUnmount_Kind)
)

func init() {
	SchemeBuilder.Register(&AdvancedClusterFileSystemUnmount{}, &AdvancedClusterFileSystemUnmountList{})
}
