/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
)

type ManagementCloudExadataInfrastructureInitParameters struct {

	// (Updatable) The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The unique key of the discovery request.
	DiscoveryKey *string `json:"discoveryKey,omitempty" tf:"discovery_key,omitempty"`

	// (Updatable) The name of the Exadata infrastructure.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The Oracle license model that applies to the database management resources.
	LicenseModel *string `json:"licenseModel,omitempty" tf:"license_model,omitempty"`

	// (Updatable) The list of all the Exadata storage server names to be included for monitoring purposes. If not specified, all the Exadata storage servers associated with the VM Clusters are included.
	StorageServerNames []*string `json:"storageServerNames,omitempty" tf:"storage_server_names,omitempty"`

	// (Updatable) The list of VM Clusters in the Exadata infrastructure.
	VMClusterIds []*string `json:"vmClusterIds,omitempty" tf:"vm_cluster_ids,omitempty"`
}

type ManagementCloudExadataInfrastructureObservation struct {

	// The additional details of the resource defined in {"key": "value"} format. Example: {"bar-key": "value"}
	// +mapType=granular
	AdditionalDetails map[string]*string `json:"additionalDetails,omitempty" tf:"additional_details,omitempty"`

	// (Updatable) The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The list of [OCIDs] (https://docs.cloud.oracle.com/iaas/Content/General/Concepts/identifiers.htm) of the compartments.
	DatabaseCompartments []*string `json:"databaseCompartments,omitempty" tf:"database_compartments,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The infrastructure deployment type.
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// (Updatable) The unique key of the discovery request.
	DiscoveryKey *string `json:"discoveryKey,omitempty" tf:"discovery_key,omitempty"`

	// (Updatable) The name of the Exadata infrastructure.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the Exadata resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	InfrastructureType *string `json:"infrastructureType,omitempty" tf:"infrastructure_type,omitempty"`

	// The internal ID of the Exadata resource.
	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// (Updatable) The Oracle license model that applies to the database management resources.
	LicenseModel *string `json:"licenseModel,omitempty" tf:"license_model,omitempty"`

	// The details of the lifecycle state of the Exadata resource.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The rack size of the Exadata infrastructure.
	RackSize *string `json:"rackSize,omitempty" tf:"rack_size,omitempty"`

	// The type of Exadata resource.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The current lifecycle state of the database resource.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The status of the Exadata resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The Exadata storage server grid of the Exadata infrastructure.
	StorageGrid []StorageGridObservation `json:"storageGrid,omitempty" tf:"storage_grid,omitempty"`

	// (Updatable) The list of all the Exadata storage server names to be included for monitoring purposes. If not specified, all the Exadata storage servers associated with the VM Clusters are included.
	StorageServerNames []*string `json:"storageServerNames,omitempty" tf:"storage_server_names,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. System tags can be viewed by users, but can only be created by the system.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The timestamp of the creation of the Exadata resource.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The timestamp of the last update of the Exadata resource.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// (Updatable) The list of VM Clusters in the Exadata infrastructure.
	VMClusterIds []*string `json:"vmClusterIds,omitempty" tf:"vm_cluster_ids,omitempty"`

	// The list of VM Clusters in the Exadata infrastructure.
	VMClusters []VMClustersObservation `json:"vmClusters,omitempty" tf:"vm_clusters,omitempty"`

	// The version of the Exadata resource.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ManagementCloudExadataInfrastructureParameters struct {

	// (Updatable) The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.Reference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.Selector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) The unique key of the discovery request.
	// +kubebuilder:validation:Optional
	DiscoveryKey *string `json:"discoveryKey,omitempty" tf:"discovery_key,omitempty"`

	// (Updatable) The name of the Exadata infrastructure.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The Oracle license model that applies to the database management resources.
	// +kubebuilder:validation:Optional
	LicenseModel *string `json:"licenseModel,omitempty" tf:"license_model,omitempty"`

	// (Updatable) The list of all the Exadata storage server names to be included for monitoring purposes. If not specified, all the Exadata storage servers associated with the VM Clusters are included.
	// +kubebuilder:validation:Optional
	StorageServerNames []*string `json:"storageServerNames,omitempty" tf:"storage_server_names,omitempty"`

	// (Updatable) The list of VM Clusters in the Exadata infrastructure.
	// +kubebuilder:validation:Optional
	VMClusterIds []*string `json:"vmClusterIds,omitempty" tf:"vm_cluster_ids,omitempty"`
}

type StorageGridInitParameters struct {
}

type StorageGridObservation struct {

	// The additional details of the resource defined in {"key": "value"} format. Example: {"bar-key": "value"}
	// +mapType=granular
	AdditionalDetails map[string]*string `json:"additionalDetails,omitempty" tf:"additional_details,omitempty"`

	// (Updatable) The name of the Exadata infrastructure.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the Exadata resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The internal ID of the Exadata resource.
	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// The details of the lifecycle state of the Exadata resource.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The type of Exadata resource.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The number of Exadata storage servers in the Exadata infrastructure.
	ServerCount *float64 `json:"serverCount,omitempty" tf:"server_count,omitempty"`

	// The current lifecycle state of the database resource.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The status of the Exadata resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The timestamp of the creation of the Exadata resource.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The timestamp of the last update of the Exadata resource.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The version of the Exadata resource.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type StorageGridParameters struct {
}

type VMClustersInitParameters struct {
}

type VMClustersObservation struct {

	// The additional details of the resource defined in {"key": "value"} format. Example: {"bar-key": "value"}
	// +mapType=granular
	AdditionalDetails map[string]*string `json:"additionalDetails,omitempty" tf:"additional_details,omitempty"`

	// (Updatable) The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// The infrastructure deployment type.
	DeploymentType *string `json:"deploymentType,omitempty" tf:"deployment_type,omitempty"`

	// (Updatable) The name of the Exadata infrastructure.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The Oracle home directory.
	HomeDirectory *string `json:"homeDirectory,omitempty" tf:"home_directory,omitempty"`

	// The OCID of the Exadata resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The internal ID of the Exadata resource.
	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// (Updatable) The Oracle license model that applies to the database management resources.
	LicenseModel *string `json:"licenseModel,omitempty" tf:"license_model,omitempty"`

	// The details of the lifecycle state of the Exadata resource.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The type of Exadata resource.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The current lifecycle state of the database resource.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The status of the Exadata resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The timestamp of the creation of the Exadata resource.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The timestamp of the last update of the Exadata resource.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The version of the Exadata resource.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type VMClustersParameters struct {
}

// ManagementCloudExadataInfrastructureSpec defines the desired state of ManagementCloudExadataInfrastructure
type ManagementCloudExadataInfrastructureSpec struct {
	v1.ResourceSpec `json:",inline"`
	ForProvider     ManagementCloudExadataInfrastructureParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagementCloudExadataInfrastructureInitParameters `json:"initProvider,omitempty"`
}

// ManagementCloudExadataInfrastructureStatus defines the observed state of ManagementCloudExadataInfrastructure.
type ManagementCloudExadataInfrastructureStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagementCloudExadataInfrastructureObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagementCloudExadataInfrastructure is the Schema for the ManagementCloudExadataInfrastructures API. Provides the Cloud Exadata Infrastructure resource in Oracle Cloud Infrastructure Database Management service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Cluster,categories={crossplane,managed,oci}
type ManagementCloudExadataInfrastructure struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.vmClusterIds) || (has(self.initProvider) && has(self.initProvider.vmClusterIds))",message="spec.forProvider.vmClusterIds is a required parameter"
	Spec   ManagementCloudExadataInfrastructureSpec   `json:"spec"`
	Status ManagementCloudExadataInfrastructureStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagementCloudExadataInfrastructureList contains a list of ManagementCloudExadataInfrastructures
type ManagementCloudExadataInfrastructureList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagementCloudExadataInfrastructure `json:"items"`
}

// Repository type metadata.
var (
	ManagementCloudExadataInfrastructure_Kind             = "ManagementCloudExadataInfrastructure"
	ManagementCloudExadataInfrastructure_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagementCloudExadataInfrastructure_Kind}.String()
	ManagementCloudExadataInfrastructure_KindAPIVersion   = ManagementCloudExadataInfrastructure_Kind + "." + CRDGroupVersion.String()
	ManagementCloudExadataInfrastructure_GroupVersionKind = CRDGroupVersion.WithKind(ManagementCloudExadataInfrastructure_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagementCloudExadataInfrastructure{}, &ManagementCloudExadataInfrastructureList{})
}
