/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this EnrollmentStatus.
func (mg *EnrollmentStatus) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EnrollmentStatusID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.EnrollmentStatusIDRef,
		Selector:     mg.Spec.ForProvider.EnrollmentStatusIDSelector,
		To: reference.To{
			List:    &EnrollmentStatusList{},
			Managed: &EnrollmentStatus{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.EnrollmentStatusID")
	}
	mg.Spec.ForProvider.EnrollmentStatusID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.EnrollmentStatusIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EnrollmentStatusID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.EnrollmentStatusIDRef,
		Selector:     mg.Spec.InitProvider.EnrollmentStatusIDSelector,
		To: reference.To{
			List:    &EnrollmentStatusList{},
			Managed: &EnrollmentStatus{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.EnrollmentStatusID")
	}
	mg.Spec.InitProvider.EnrollmentStatusID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.EnrollmentStatusIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Profile.
func (mg *Profile) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.LevelsConfiguration); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.LevelsConfiguration[i3].Items); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.LevelsConfiguration[i3].Items[i4].RecommendationID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.LevelsConfiguration[i3].Items[i4].RecommendationIDRef,
				Selector:     mg.Spec.ForProvider.LevelsConfiguration[i3].Items[i4].RecommendationIDSelector,
				To: reference.To{
					List:    &RecommendationList{},
					Managed: &Recommendation{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.LevelsConfiguration[i3].Items[i4].RecommendationID")
			}
			mg.Spec.ForProvider.LevelsConfiguration[i3].Items[i4].RecommendationID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.LevelsConfiguration[i3].Items[i4].RecommendationIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.TargetTags); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.TargetTags[i3].Items); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.TargetTags[i3].Items[i4].TagNamespaceName),
				Extract:      resource.ExtractParamPath("name", false),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.TargetTags[i3].Items[i4].TagNamespaceNameRef,
				Selector:     mg.Spec.ForProvider.TargetTags[i3].Items[i4].TagNamespaceNameSelector,
				To: reference.To{
					List:    &v1alpha1.TagNamespaceList{},
					Managed: &v1alpha1.TagNamespace{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.TargetTags[i3].Items[i4].TagNamespaceName")
			}
			mg.Spec.ForProvider.TargetTags[i3].Items[i4].TagNamespaceName = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.TargetTags[i3].Items[i4].TagNamespaceNameRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.LevelsConfiguration); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.LevelsConfiguration[i3].Items); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.LevelsConfiguration[i3].Items[i4].RecommendationID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.LevelsConfiguration[i3].Items[i4].RecommendationIDRef,
				Selector:     mg.Spec.InitProvider.LevelsConfiguration[i3].Items[i4].RecommendationIDSelector,
				To: reference.To{
					List:    &RecommendationList{},
					Managed: &Recommendation{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.LevelsConfiguration[i3].Items[i4].RecommendationID")
			}
			mg.Spec.InitProvider.LevelsConfiguration[i3].Items[i4].RecommendationID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.LevelsConfiguration[i3].Items[i4].RecommendationIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.TargetTags); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.TargetTags[i3].Items); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.TargetTags[i3].Items[i4].TagNamespaceName),
				Extract:      resource.ExtractParamPath("name", false),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.TargetTags[i3].Items[i4].TagNamespaceNameRef,
				Selector:     mg.Spec.InitProvider.TargetTags[i3].Items[i4].TagNamespaceNameSelector,
				To: reference.To{
					List:    &v1alpha1.TagNamespaceList{},
					Managed: &v1alpha1.TagNamespace{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.TargetTags[i3].Items[i4].TagNamespaceName")
			}
			mg.Spec.InitProvider.TargetTags[i3].Items[i4].TagNamespaceName = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.TargetTags[i3].Items[i4].TagNamespaceNameRef = rsp.ResolvedReference

		}
	}

	return nil
}

// ResolveReferences of this Recommendation.
func (mg *Recommendation) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.RecommendationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.RecommendationIDRef,
		Selector:     mg.Spec.ForProvider.RecommendationIDSelector,
		To: reference.To{
			List:    &RecommendationList{},
			Managed: &Recommendation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.RecommendationID")
	}
	mg.Spec.ForProvider.RecommendationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.RecommendationIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.RecommendationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.RecommendationIDRef,
		Selector:     mg.Spec.InitProvider.RecommendationIDSelector,
		To: reference.To{
			List:    &RecommendationList{},
			Managed: &Recommendation{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.RecommendationID")
	}
	mg.Spec.InitProvider.RecommendationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.RecommendationIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ResourceAction.
func (mg *ResourceAction) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ResourceActionID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ResourceActionIDRef,
		Selector:     mg.Spec.ForProvider.ResourceActionIDSelector,
		To: reference.To{
			List:    &ResourceActionList{},
			Managed: &ResourceAction{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ResourceActionID")
	}
	mg.Spec.ForProvider.ResourceActionID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ResourceActionIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ResourceActionID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ResourceActionIDRef,
		Selector:     mg.Spec.InitProvider.ResourceActionIDSelector,
		To: reference.To{
			List:    &ResourceActionList{},
			Managed: &ResourceAction{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ResourceActionID")
	}
	mg.Spec.InitProvider.ResourceActionID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ResourceActionIDRef = rsp.ResolvedReference

	return nil
}
