/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha13 "github.com/oracle/provider-oci/apis/namespaced/apigateway/v1alpha1"
	v1alpha11 "github.com/oracle/provider-oci/apis/namespaced/audit/v1alpha1"
	v1alpha1 "github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1"
	v1alpha12 "github.com/oracle/provider-oci/apis/namespaced/kms/v1alpha1"
	v1alpha14 "github.com/oracle/provider-oci/apis/namespaced/networking/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this MysqlBackup.
func (mg *MysqlBackup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DBSystemID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DBSystemIDRef,
		Selector:     mg.Spec.ForProvider.DBSystemIDSelector,
		To: reference.To{
			List:    &MysqlDbSystemList{},
			Managed: &MysqlDbSystem{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DBSystemID")
	}
	mg.Spec.ForProvider.DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DBSystemIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DBSystemID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DBSystemIDRef,
		Selector:     mg.Spec.InitProvider.DBSystemIDSelector,
		To: reference.To{
			List:    &MysqlDbSystemList{},
			Managed: &MysqlDbSystem{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DBSystemID")
	}
	mg.Spec.InitProvider.DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DBSystemIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MysqlChannel.
func (mg *MysqlChannel) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Target); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Target[i3].ChannelName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Target[i3].ChannelNameRef,
			Selector:     mg.Spec.ForProvider.Target[i3].ChannelNameSelector,
			To: reference.To{
				List:    &MysqlChannelList{},
				Managed: &MysqlChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Target[i3].ChannelName")
		}
		mg.Spec.ForProvider.Target[i3].ChannelName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Target[i3].ChannelNameRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Target); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Target[i3].DBSystemID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Target[i3].DBSystemIDRef,
			Selector:     mg.Spec.ForProvider.Target[i3].DBSystemIDSelector,
			To: reference.To{
				List:    &MysqlDbSystemList{},
				Managed: &MysqlDbSystem{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Target[i3].DBSystemID")
		}
		mg.Spec.ForProvider.Target[i3].DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Target[i3].DBSystemIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.Target); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Target[i3].ChannelName),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Target[i3].ChannelNameRef,
			Selector:     mg.Spec.InitProvider.Target[i3].ChannelNameSelector,
			To: reference.To{
				List:    &MysqlChannelList{},
				Managed: &MysqlChannel{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Target[i3].ChannelName")
		}
		mg.Spec.InitProvider.Target[i3].ChannelName = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Target[i3].ChannelNameRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Target); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Target[i3].DBSystemID),
			Extract:      reference.ExternalName(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Target[i3].DBSystemIDRef,
			Selector:     mg.Spec.InitProvider.Target[i3].DBSystemIDSelector,
			To: reference.To{
				List:    &MysqlDbSystemList{},
				Managed: &MysqlDbSystem{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Target[i3].DBSystemID")
		}
		mg.Spec.InitProvider.Target[i3].DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Target[i3].DBSystemIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this MysqlConfiguration.
func (mg *MysqlConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ParentConfigurationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ParentConfigurationIDRef,
		Selector:     mg.Spec.ForProvider.ParentConfigurationIDSelector,
		To: reference.To{
			List:    &v1alpha11.ConfigurationList{},
			Managed: &v1alpha11.Configuration{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ParentConfigurationID")
	}
	mg.Spec.ForProvider.ParentConfigurationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ParentConfigurationIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ParentConfigurationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ParentConfigurationIDRef,
		Selector:     mg.Spec.InitProvider.ParentConfigurationIDSelector,
		To: reference.To{
			List:    &v1alpha11.ConfigurationList{},
			Managed: &v1alpha11.Configuration{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ParentConfigurationID")
	}
	mg.Spec.InitProvider.ParentConfigurationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ParentConfigurationIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MysqlDbSystem.
func (mg *MysqlDbSystem) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfigurationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ConfigurationIDRef,
		Selector:     mg.Spec.ForProvider.ConfigurationIDSelector,
		To: reference.To{
			List:    &v1alpha11.ConfigurationList{},
			Managed: &v1alpha11.Configuration{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfigurationID")
	}
	mg.Spec.ForProvider.ConfigurationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfigurationIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.EncryptData); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EncryptData[i3].KeyID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.EncryptData[i3].KeyIDRef,
			Selector:     mg.Spec.ForProvider.EncryptData[i3].KeyIDSelector,
			To: reference.To{
				List:    &v1alpha12.KeyList{},
				Managed: &v1alpha12.Key{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.EncryptData[i3].KeyID")
		}
		mg.Spec.ForProvider.EncryptData[i3].KeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.EncryptData[i3].KeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.SecureConnections); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SecureConnections[i3].CertificateID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.SecureConnections[i3].CertificateIDRef,
			Selector:     mg.Spec.ForProvider.SecureConnections[i3].CertificateIDSelector,
			To: reference.To{
				List:    &v1alpha13.CertificateList{},
				Managed: &v1alpha13.Certificate{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.SecureConnections[i3].CertificateID")
		}
		mg.Spec.ForProvider.SecureConnections[i3].CertificateID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.SecureConnections[i3].CertificateIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.Source); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Source[i3].BackupID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Source[i3].BackupIDRef,
			Selector:     mg.Spec.ForProvider.Source[i3].BackupIDSelector,
			To: reference.To{
				List:    &MysqlBackupList{},
				Managed: &MysqlBackup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Source[i3].BackupID")
		}
		mg.Spec.ForProvider.Source[i3].BackupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Source[i3].BackupIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SubnetID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SubnetIDRef,
		Selector:     mg.Spec.ForProvider.SubnetIDSelector,
		To: reference.To{
			List:    &v1alpha14.SubnetList{},
			Managed: &v1alpha14.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SubnetID")
	}
	mg.Spec.ForProvider.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SubnetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfigurationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ConfigurationIDRef,
		Selector:     mg.Spec.InitProvider.ConfigurationIDSelector,
		To: reference.To{
			List:    &v1alpha11.ConfigurationList{},
			Managed: &v1alpha11.Configuration{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfigurationID")
	}
	mg.Spec.InitProvider.ConfigurationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfigurationIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.EncryptData); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EncryptData[i3].KeyID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.EncryptData[i3].KeyIDRef,
			Selector:     mg.Spec.InitProvider.EncryptData[i3].KeyIDSelector,
			To: reference.To{
				List:    &v1alpha12.KeyList{},
				Managed: &v1alpha12.Key{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.EncryptData[i3].KeyID")
		}
		mg.Spec.InitProvider.EncryptData[i3].KeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.EncryptData[i3].KeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.SecureConnections); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SecureConnections[i3].CertificateID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.SecureConnections[i3].CertificateIDRef,
			Selector:     mg.Spec.InitProvider.SecureConnections[i3].CertificateIDSelector,
			To: reference.To{
				List:    &v1alpha13.CertificateList{},
				Managed: &v1alpha13.Certificate{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.SecureConnections[i3].CertificateID")
		}
		mg.Spec.InitProvider.SecureConnections[i3].CertificateID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.SecureConnections[i3].CertificateIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Source); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Source[i3].BackupID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Source[i3].BackupIDRef,
			Selector:     mg.Spec.InitProvider.Source[i3].BackupIDSelector,
			To: reference.To{
				List:    &MysqlBackupList{},
				Managed: &MysqlBackup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Source[i3].BackupID")
		}
		mg.Spec.InitProvider.Source[i3].BackupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Source[i3].BackupIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SubnetID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SubnetIDRef,
		Selector:     mg.Spec.InitProvider.SubnetIDSelector,
		To: reference.To{
			List:    &v1alpha14.SubnetList{},
			Managed: &v1alpha14.Subnet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SubnetID")
	}
	mg.Spec.InitProvider.SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SubnetIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MysqlHeatWaveCluster.
func (mg *MysqlHeatWaveCluster) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DBSystemID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DBSystemIDRef,
		Selector:     mg.Spec.ForProvider.DBSystemIDSelector,
		To: reference.To{
			List:    &MysqlDbSystemList{},
			Managed: &MysqlDbSystem{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DBSystemID")
	}
	mg.Spec.ForProvider.DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DBSystemIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DBSystemID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DBSystemIDRef,
		Selector:     mg.Spec.InitProvider.DBSystemIDSelector,
		To: reference.To{
			List:    &MysqlDbSystemList{},
			Managed: &MysqlDbSystem{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DBSystemID")
	}
	mg.Spec.InitProvider.DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DBSystemIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MysqlReplica.
func (mg *MysqlReplica) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DBSystemID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DBSystemIDRef,
		Selector:     mg.Spec.ForProvider.DBSystemIDSelector,
		To: reference.To{
			List:    &MysqlDbSystemList{},
			Managed: &MysqlDbSystem{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DBSystemID")
	}
	mg.Spec.ForProvider.DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DBSystemIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ReplicaOverrides); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ReplicaOverrides[i3].ConfigurationID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ReplicaOverrides[i3].ConfigurationIDRef,
			Selector:     mg.Spec.ForProvider.ReplicaOverrides[i3].ConfigurationIDSelector,
			To: reference.To{
				List:    &MysqlConfigurationList{},
				Managed: &MysqlConfiguration{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ReplicaOverrides[i3].ConfigurationID")
		}
		mg.Spec.ForProvider.ReplicaOverrides[i3].ConfigurationID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ReplicaOverrides[i3].ConfigurationIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DBSystemID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DBSystemIDRef,
		Selector:     mg.Spec.InitProvider.DBSystemIDSelector,
		To: reference.To{
			List:    &MysqlDbSystemList{},
			Managed: &MysqlDbSystem{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DBSystemID")
	}
	mg.Spec.InitProvider.DBSystemID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DBSystemIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.ReplicaOverrides); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ReplicaOverrides[i3].ConfigurationID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ReplicaOverrides[i3].ConfigurationIDRef,
			Selector:     mg.Spec.InitProvider.ReplicaOverrides[i3].ConfigurationIDSelector,
			To: reference.To{
				List:    &MysqlConfigurationList{},
				Managed: &MysqlConfiguration{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ReplicaOverrides[i3].ConfigurationID")
		}
		mg.Spec.InitProvider.ReplicaOverrides[i3].ConfigurationID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ReplicaOverrides[i3].ConfigurationIDRef = rsp.ResolvedReference

	}

	return nil
}
