---
apiVersion: mysql.oci.m.upbound.io/v1alpha1
kind: MysqlDbSystem
metadata:
  labels:
    testing.upbound.io/example-name: mysqldbsystem_label_1
  name: mysqldbsystem1
  namespace: crossplane-system
spec:
  forProvider:
    adminPasswordSecretRef:
      key: example-key
      name: mysql-db-admin-secret
    adminUsername: myadminuser
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: mysqldbsystem1
    shapeName: MySQL.2
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_label_2
