---
apiVersion: mysql.oci.m.upbound.io/v1alpha1
kind: MysqlBackup
metadata:
  labels:
    testing.upbound.io/example-name: mysqlbackup_label_1
  name: mysqlbackup1
  namespace: crossplane-system
spec:
  forProvider:
    dbSystemIdSelector:
      matchLabels:
        testing.upbound.io/example-name: mysqldbsystem_label_1
    displayName: mysqlbackup1
