---
apiVersion: mysql.oci.m.upbound.io/v1alpha1
kind: MysqlConfiguration
metadata:
  labels:
    testing.upbound.io/example-name: mysqlconfiguration_label_1
  name: mysqlconfiguration1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: mysqlconfiguration1
    shapeName: MySQL.2
