/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type BatchContextInitParameters struct {

	// (Updatable) The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Summarized information about the batch context.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. If not specified or provided as null or empty string, it will be generated as "", where timeCreated corresponds with the resource creation time in ISO 8601 basic format, i.e. omitting separating punctuation, at second-level precision and no UTC offset. Example: batchcontext20250914115623.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Mapping of concurrent/shared resources used in job tasks to their limits.
	// +mapType=granular
	Entitlements map[string]*string `json:"entitlements,omitempty" tf:"entitlements,omitempty"`

	// List of fleet configurations related to the batch context.
	Fleets []FleetsInitParameters `json:"fleets,omitempty" tf:"fleets,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) List of job priority configurations related to the batch context.
	JobPriorityConfigurations []JobPriorityConfigurationsInitParameters `json:"jobPriorityConfigurations,omitempty" tf:"job_priority_configurations,omitempty"`

	// Logging configuration for batch context.
	LoggingConfiguration []LoggingConfigurationInitParameters `json:"loggingConfiguration,omitempty" tf:"logging_configuration,omitempty"`

	// Network configuration of the batch context.
	Network []NetworkInitParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (Updatable) The target state for the Batch Context. Could be set to ACTIVE or INACTIVE.
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type BatchContextObservation struct {

	// (Updatable) The OCID of the compartment.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Summarized information about the batch context.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. If not specified or provided as null or empty string, it will be generated as "", where timeCreated corresponds with the resource creation time in ISO 8601 basic format, i.e. omitting separating punctuation, at second-level precision and no UTC offset. Example: batchcontext20250914115623.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Mapping of concurrent/shared resources used in job tasks to their limits.
	// +mapType=granular
	Entitlements map[string]*string `json:"entitlements,omitempty" tf:"entitlements,omitempty"`

	// List of fleet configurations related to the batch context.
	Fleets []FleetsObservation `json:"fleets,omitempty" tf:"fleets,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the batch context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) List of job priority configurations related to the batch context.
	JobPriorityConfigurations []JobPriorityConfigurationsObservation `json:"jobPriorityConfigurations,omitempty" tf:"job_priority_configurations,omitempty"`

	// A message that describes the current state in more detail. For example,   can be used to provide actionable information for a resource in the Failed state.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// Logging configuration for batch context.
	LoggingConfiguration []LoggingConfigurationObservation `json:"loggingConfiguration,omitempty" tf:"logging_configuration,omitempty"`

	// Network configuration of the batch context.
	Network []NetworkObservation `json:"network,omitempty" tf:"network,omitempty"`

	// (Updatable) The target state for the Batch Context. Could be set to ACTIVE or INACTIVE.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The date and time the batch context was created, in the format defined by RFC 3339.  Example: 2016-08-25T21:10:29.600Z
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The date and time the batch context was updated, in the format defined by RFC 3339.  Example: 2016-08-25T21:10:29.600Z
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type BatchContextParameters struct {

	// (Updatable) The OCID of the compartment.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags.  Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Summarized information about the batch context.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable. If not specified or provided as null or empty string, it will be generated as "", where timeCreated corresponds with the resource creation time in ISO 8601 basic format, i.e. omitting separating punctuation, at second-level precision and no UTC offset. Example: batchcontext20250914115623.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Mapping of concurrent/shared resources used in job tasks to their limits.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Entitlements map[string]*string `json:"entitlements,omitempty" tf:"entitlements,omitempty"`

	// List of fleet configurations related to the batch context.
	// +kubebuilder:validation:Optional
	Fleets []FleetsParameters `json:"fleets,omitempty" tf:"fleets,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags.  Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) List of job priority configurations related to the batch context.
	// +kubebuilder:validation:Optional
	JobPriorityConfigurations []JobPriorityConfigurationsParameters `json:"jobPriorityConfigurations,omitempty" tf:"job_priority_configurations,omitempty"`

	// Logging configuration for batch context.
	// +kubebuilder:validation:Optional
	LoggingConfiguration []LoggingConfigurationParameters `json:"loggingConfiguration,omitempty" tf:"logging_configuration,omitempty"`

	// Network configuration of the batch context.
	// +kubebuilder:validation:Optional
	Network []NetworkParameters `json:"network,omitempty" tf:"network,omitempty"`

	// (Updatable) The target state for the Batch Context. Could be set to ACTIVE or INACTIVE.
	// +kubebuilder:validation:Optional
	State *string `json:"state,omitempty" tf:"state,omitempty"`
}

type FleetsInitParameters struct {

	// Maximum number of concurrent tasks for the service managed fleet.
	MaxConcurrentTasks *float64 `json:"maxConcurrentTasks,omitempty" tf:"max_concurrent_tasks,omitempty"`

	// Name of the service managed fleet.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Shape of the fleet. Describes hardware resources of each node in the fleet.
	Shape []ShapeInitParameters `json:"shape,omitempty" tf:"shape,omitempty"`

	// Type of the fleet. Also serves as a discriminator for sub-entities.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FleetsObservation struct {

	// A message that describes the current state of the service manage fleet configuration in more detail.
	Details *string `json:"details,omitempty" tf:"details,omitempty"`

	// Maximum number of concurrent tasks for the service managed fleet.
	MaxConcurrentTasks *float64 `json:"maxConcurrentTasks,omitempty" tf:"max_concurrent_tasks,omitempty"`

	// Name of the service managed fleet.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// Shape of the fleet. Describes hardware resources of each node in the fleet.
	Shape []ShapeObservation `json:"shape,omitempty" tf:"shape,omitempty"`

	// (Updatable) The target state for the Batch Context. Could be set to ACTIVE or INACTIVE.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Type of the fleet. Also serves as a discriminator for sub-entities.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type FleetsParameters struct {

	// Maximum number of concurrent tasks for the service managed fleet.
	// +kubebuilder:validation:Optional
	MaxConcurrentTasks *float64 `json:"maxConcurrentTasks" tf:"max_concurrent_tasks,omitempty"`

	// Name of the service managed fleet.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// Shape of the fleet. Describes hardware resources of each node in the fleet.
	// +kubebuilder:validation:Optional
	Shape []ShapeParameters `json:"shape" tf:"shape,omitempty"`

	// Type of the fleet. Also serves as a discriminator for sub-entities.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type JobPriorityConfigurationsInitParameters struct {

	// (Updatable) Name of the tag key.
	TagKey *string `json:"tagKey,omitempty" tf:"tag_key,omitempty"`

	// (Updatable) Name of the corresponding tag namespace.
	TagNamespace *string `json:"tagNamespace,omitempty" tf:"tag_namespace,omitempty"`

	// (Updatable) Mapping of tag value to its priority.
	// +mapType=granular
	Values map[string]*string `json:"values,omitempty" tf:"values,omitempty"`

	// (Updatable) Weight associated with the tag key. Percentage point is the unit of measurement.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type JobPriorityConfigurationsObservation struct {

	// (Updatable) Name of the tag key.
	TagKey *string `json:"tagKey,omitempty" tf:"tag_key,omitempty"`

	// (Updatable) Name of the corresponding tag namespace.
	TagNamespace *string `json:"tagNamespace,omitempty" tf:"tag_namespace,omitempty"`

	// (Updatable) Mapping of tag value to its priority.
	// +mapType=granular
	Values map[string]*string `json:"values,omitempty" tf:"values,omitempty"`

	// (Updatable) Weight associated with the tag key. Percentage point is the unit of measurement.
	Weight *float64 `json:"weight,omitempty" tf:"weight,omitempty"`
}

type JobPriorityConfigurationsParameters struct {

	// (Updatable) Name of the tag key.
	// +kubebuilder:validation:Optional
	TagKey *string `json:"tagKey" tf:"tag_key,omitempty"`

	// (Updatable) Name of the corresponding tag namespace.
	// +kubebuilder:validation:Optional
	TagNamespace *string `json:"tagNamespace" tf:"tag_namespace,omitempty"`

	// (Updatable) Mapping of tag value to its priority.
	// +kubebuilder:validation:Optional
	// +mapType=granular
	Values map[string]*string `json:"values" tf:"values,omitempty"`

	// (Updatable) Weight associated with the tag key. Percentage point is the unit of measurement.
	// +kubebuilder:validation:Optional
	Weight *float64 `json:"weight" tf:"weight,omitempty"`
}

type LoggingConfigurationInitParameters struct {

	// The OCID of the log group.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/logging/v1alpha1.LogGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	LogGroupID *string `json:"logGroupId,omitempty" tf:"log_group_id,omitempty"`

	// Reference to a LogGroup in logging to populate logGroupId.
	// +kubebuilder:validation:Optional
	LogGroupIDRef *v1.NamespacedReference `json:"logGroupIdRef,omitempty" tf:"-"`

	// Selector for a LogGroup in logging to populate logGroupId.
	// +kubebuilder:validation:Optional
	LogGroupIDSelector *v1.NamespacedSelector `json:"logGroupIdSelector,omitempty" tf:"-"`

	// The OCID of the log.
	LogID *string `json:"logId,omitempty" tf:"log_id,omitempty"`

	// Type of the fleet. Also serves as a discriminator for sub-entities.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LoggingConfigurationObservation struct {

	// The OCID of the log group.
	LogGroupID *string `json:"logGroupId,omitempty" tf:"log_group_id,omitempty"`

	// The OCID of the log.
	LogID *string `json:"logId,omitempty" tf:"log_id,omitempty"`

	// Type of the fleet. Also serves as a discriminator for sub-entities.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type LoggingConfigurationParameters struct {

	// The OCID of the log group.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/logging/v1alpha1.LogGroup
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	LogGroupID *string `json:"logGroupId,omitempty" tf:"log_group_id,omitempty"`

	// Reference to a LogGroup in logging to populate logGroupId.
	// +kubebuilder:validation:Optional
	LogGroupIDRef *v1.NamespacedReference `json:"logGroupIdRef,omitempty" tf:"-"`

	// Selector for a LogGroup in logging to populate logGroupId.
	// +kubebuilder:validation:Optional
	LogGroupIDSelector *v1.NamespacedSelector `json:"logGroupIdSelector,omitempty" tf:"-"`

	// The OCID of the log.
	// +kubebuilder:validation:Optional
	LogID *string `json:"logId" tf:"log_id,omitempty"`

	// Type of the fleet. Also serves as a discriminator for sub-entities.
	// +kubebuilder:validation:Optional
	Type *string `json:"type" tf:"type,omitempty"`
}

type NetworkInitParameters struct {

	// A list of OCIDs of associated network security groups.
	// +listType=set
	NsgIds []*string `json:"nsgIds,omitempty" tf:"nsg_ids,omitempty"`

	// OCID of associated subnet.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/networking/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in networking to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in networking to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type NetworkObservation struct {

	// A list of OCIDs of associated network security groups.
	// +listType=set
	NsgIds []*string `json:"nsgIds,omitempty" tf:"nsg_ids,omitempty"`

	// OCID of associated subnet.
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// A list of private endpoint's VNICs.
	Vnics []VnicsObservation `json:"vnics,omitempty" tf:"vnics,omitempty"`
}

type NetworkParameters struct {

	// A list of OCIDs of associated network security groups.
	// +kubebuilder:validation:Optional
	// +listType=set
	NsgIds []*string `json:"nsgIds,omitempty" tf:"nsg_ids,omitempty"`

	// OCID of associated subnet.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/networking/v1alpha1.Subnet
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	SubnetID *string `json:"subnetId,omitempty" tf:"subnet_id,omitempty"`

	// Reference to a Subnet in networking to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDRef *v1.NamespacedReference `json:"subnetIdRef,omitempty" tf:"-"`

	// Selector for a Subnet in networking to populate subnetId.
	// +kubebuilder:validation:Optional
	SubnetIDSelector *v1.NamespacedSelector `json:"subnetIdSelector,omitempty" tf:"-"`
}

type ShapeInitParameters struct {

	// Amount of memory in GBs required by the shape.
	MemoryInGbs *float64 `json:"memoryInGbs,omitempty" tf:"memory_in_gbs,omitempty"`

	// Number of OCPUs required by the shape.
	Ocpus *float64 `json:"ocpus,omitempty" tf:"ocpus,omitempty"`

	// The name of the shape.
	ShapeName *string `json:"shapeName,omitempty" tf:"shape_name,omitempty"`
}

type ShapeObservation struct {

	// Amount of memory in GBs required by the shape.
	MemoryInGbs *float64 `json:"memoryInGbs,omitempty" tf:"memory_in_gbs,omitempty"`

	// Number of OCPUs required by the shape.
	Ocpus *float64 `json:"ocpus,omitempty" tf:"ocpus,omitempty"`

	// The name of the shape.
	ShapeName *string `json:"shapeName,omitempty" tf:"shape_name,omitempty"`
}

type ShapeParameters struct {

	// Amount of memory in GBs required by the shape.
	// +kubebuilder:validation:Optional
	MemoryInGbs *float64 `json:"memoryInGbs" tf:"memory_in_gbs,omitempty"`

	// Number of OCPUs required by the shape.
	// +kubebuilder:validation:Optional
	Ocpus *float64 `json:"ocpus" tf:"ocpus,omitempty"`

	// The name of the shape.
	// +kubebuilder:validation:Optional
	ShapeName *string `json:"shapeName" tf:"shape_name,omitempty"`
}

type VnicsInitParameters struct {
}

type VnicsObservation struct {

	// The OCID of the batch context.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// A list of private IP addresses (in the customer's VCN) that represent access points for the service.
	SourceIps []*string `json:"sourceIps,omitempty" tf:"source_ips,omitempty"`
}

type VnicsParameters struct {
}

// BatchContextSpec defines the desired state of BatchContext
type BatchContextSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            BatchContextParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider BatchContextInitParameters `json:"initProvider,omitempty"`
}

// BatchContextStatus defines the observed state of BatchContext.
type BatchContextStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        BatchContextObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// BatchContext is the Schema for the BatchContexts API. Provides the Batch Context resource in Oracle Cloud Infrastructure Batch service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type BatchContext struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.fleets) || (has(self.initProvider) && has(self.initProvider.fleets))",message="spec.forProvider.fleets is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.network) || (has(self.initProvider) && has(self.initProvider.network))",message="spec.forProvider.network is a required parameter"
	Spec   BatchContextSpec   `json:"spec"`
	Status BatchContextStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// BatchContextList contains a list of BatchContexts
type BatchContextList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []BatchContext `json:"items"`
}

// Repository type metadata.
var (
	BatchContext_Kind             = "BatchContext"
	BatchContext_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: BatchContext_Kind}.String()
	BatchContext_KindAPIVersion   = BatchContext_Kind + "." + CRDGroupVersion.String()
	BatchContext_GroupVersionKind = CRDGroupVersion.WithKind(BatchContext_Kind)
)

func init() {
	SchemeBuilder.Register(&BatchContext{}, &BatchContextList{})
}
