/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha11 "github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1"
	v1alpha1 "github.com/oracle/provider-oci/apis/cluster/vault/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this IntegrationInstance.
func (mg *IntegrationInstance) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.AlternateCustomEndpoints); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AlternateCustomEndpoints[i3].CertificateSecretID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.AlternateCustomEndpoints[i3].CertificateSecretIDRef,
			Selector:     mg.Spec.ForProvider.AlternateCustomEndpoints[i3].CertificateSecretIDSelector,
			To: reference.To{
				List:    &v1alpha1.SecretList{},
				Managed: &v1alpha1.Secret{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.AlternateCustomEndpoints[i3].CertificateSecretID")
		}
		mg.Spec.ForProvider.AlternateCustomEndpoints[i3].CertificateSecretID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.AlternateCustomEndpoints[i3].CertificateSecretIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha11.CompartmentList{},
			Managed: &v1alpha11.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.CustomEndpoint); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CustomEndpoint[i3].CertificateSecretID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.CustomEndpoint[i3].CertificateSecretIDRef,
			Selector:     mg.Spec.ForProvider.CustomEndpoint[i3].CertificateSecretIDSelector,
			To: reference.To{
				List:    &v1alpha1.SecretList{},
				Managed: &v1alpha1.Secret{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.CustomEndpoint[i3].CertificateSecretID")
		}
		mg.Spec.ForProvider.CustomEndpoint[i3].CertificateSecretID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.CustomEndpoint[i3].CertificateSecretIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.DomainID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.DomainIDRef,
		Selector:     mg.Spec.ForProvider.DomainIDSelector,
		To: reference.To{
			List:    &v1alpha11.DomainList{},
			Managed: &v1alpha11.Domain{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.DomainID")
	}
	mg.Spec.ForProvider.DomainID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.DomainIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.AlternateCustomEndpoints); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AlternateCustomEndpoints[i3].CertificateSecretID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.AlternateCustomEndpoints[i3].CertificateSecretIDRef,
			Selector:     mg.Spec.InitProvider.AlternateCustomEndpoints[i3].CertificateSecretIDSelector,
			To: reference.To{
				List:    &v1alpha1.SecretList{},
				Managed: &v1alpha1.Secret{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.AlternateCustomEndpoints[i3].CertificateSecretID")
		}
		mg.Spec.InitProvider.AlternateCustomEndpoints[i3].CertificateSecretID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.AlternateCustomEndpoints[i3].CertificateSecretIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha11.CompartmentList{},
			Managed: &v1alpha11.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.CustomEndpoint); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CustomEndpoint[i3].CertificateSecretID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.CustomEndpoint[i3].CertificateSecretIDRef,
			Selector:     mg.Spec.InitProvider.CustomEndpoint[i3].CertificateSecretIDSelector,
			To: reference.To{
				List:    &v1alpha1.SecretList{},
				Managed: &v1alpha1.Secret{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.CustomEndpoint[i3].CertificateSecretID")
		}
		mg.Spec.InitProvider.CustomEndpoint[i3].CertificateSecretID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.CustomEndpoint[i3].CertificateSecretIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.DomainID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.DomainIDRef,
		Selector:     mg.Spec.InitProvider.DomainIDSelector,
		To: reference.To{
			List:    &v1alpha11.DomainList{},
			Managed: &v1alpha11.Domain{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.DomainID")
	}
	mg.Spec.InitProvider.DomainID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.DomainIDRef = rsp.ResolvedReference

	return nil
}
