---
apiVersion: recovery.oci.m.upbound.io/v1alpha1
kind: ProtectionPolicy
metadata:
  labels:
    testing.upbound.io/example-name: protectionpolicy_label_1
  name: protectionpolicy1
  namespace: crossplane-system
spec:
  forProvider:
    backupRetentionPeriodInDays: 30
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: protectionpolicy1
