---
apiVersion: recovery.oci.m.upbound.io/v1alpha1
kind: ProtectedDatabase
metadata:
  labels:
    testing.upbound.io/example-name: protecteddatabase_label_1
  name: protecteddatabase1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    dbUniqueName: TESTDB
    displayName: protecteddatabase1
    passwordSecretRef:
      key: password
      name: protected-db-secret
    protectionPolicyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: protectionpolicy_label_1
    recoveryServiceSubnets:
    - recoveryServiceSubnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: recoveryservicesubnet_label_1
