---
apiVersion: recovery.oci.m.upbound.io/v1alpha1
kind: RecoveryServiceSubnet
metadata:
  labels:
    testing.upbound.io/example-name: recoveryservicesubnet_label_1
  name: recoveryservicesubnet1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: recoveryservicesubnet1
    subnets:
    - ${SUBNET_OCID}
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn_label_1
