---
apiVersion: network.oci.m.upbound.io/v1alpha1
kind: FirewallNetworkFirewall
metadata:
  name: nwfw-via-crossplane
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdRef:
      name: compartment-via-crossplane1
    networkFirewallPolicyIdRef:
      name: nwfwpolicy-via-crossplane
    subnetIdRef:
      name: subnet-via-crossplane
