---
apiVersion: network.oci.m.upbound.io/v1alpha1
kind: FirewallNetworkFirewallPolicy
metadata:
  name: nwfwpolicy-via-crossplane
  namespace: crossplane-system
spec:
  forProvider:
    applicationLists:
    - key: appList1
      maximumPort: 100
      minimumPort: 0
      type: TCP
    compartmentIdRef:
      name: compartment-via-crossplane1
    decryptionProfiles:
    - key: decrypt
      type: SslInboundInspection
    decryptionRules:
    - action: NO_DECRYPT
      condition:
      - destinations:
        - ipa
        sources:
        - ipb
      name: test-security-rules
    ipAddressLists:
    - ipAddressListName: ipa
      ipAddressListValue:
      - 1.1.1.1
      - 2.2.2.2
    - ipAddressListName: ipb
      ipAddressListValue:
      - 1.2.2.1
      - 2.2.3.2
    securityRules:
    - action: ALLOW
      condition:
      - applications:
        - appList1
        destinations:
        - ipa
        sources:
        - ipb
      name: security-rules
