apiVersion: distributed.oci.upbound.io/v1alpha1
kind: DatabaseDistributedAutonomousDatabase
metadata:
  annotations:
    meta.upbound.io/example-id: distributed/v1alpha1/databasedistributedautonomousdatabase
  labels:
    testing.upbound.io/example-name: test_distributed_autonomous_database
  name: test-distributed-autonomous-database
spec:
  forProvider:
    catalogDetails:
    - adminPasswordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      cloudAutonomousVmClusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
      computeCount: ${var.distributed_autonomous_database_catalog_details_compute_count}
      dataStorageSizeInGbs: ${var.distributed_autonomous_database_catalog_details_data_storage_size_in_gbs}
      isAutoScalingEnabled: ${var.distributed_autonomous_database_catalog_details_is_auto_scaling_enabled}
      kmsKeyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key
      kmsKeyVersionIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key_version
      peerCloudAutonomousVmClusterIds: ${var.distributed_autonomous_database_catalog_details_peer_cloud_autonomous_vm_cluster_ids}
      peerDetails:
      - cloudAutonomousVmClusterIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
        fastStartFailOverLagLimitInSeconds: ${var.distributed_autonomous_database_catalog_details_peer_details_fast_start_fail_over_lag_limit_in_seconds}
        isAutomaticFailoverEnabled: ${var.distributed_autonomous_database_catalog_details_peer_details_is_automatic_failover_enabled}
        protectionMode: ${var.distributed_autonomous_database_catalog_details_peer_details_protection_mode}
        standbyMaintenanceBufferInDays: ${var.distributed_autonomous_database_catalog_details_peer_details_standby_maintenance_buffer_in_days}
      source: ${var.distributed_autonomous_database_catalog_details_source}
      vaultIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vault
    characterSet: ${var.distributed_autonomous_database_character_set}
    chunks: ${var.distributed_autonomous_database_chunks}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    databaseVersion: ${var.distributed_autonomous_database_database_version}
    dbBackupConfig:
    - backupDestinationDetails:
      - dbrsPolicyIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_policy
        id: ${var.distributed_autonomous_database_db_backup_config_backup_destination_details_id}
        internetProxy: ${var.distributed_autonomous_database_db_backup_config_backup_destination_details_internet_proxy}
        isRemote: ${var.distributed_autonomous_database_db_backup_config_backup_destination_details_is_remote}
        remoteRegion: ${var.distributed_autonomous_database_db_backup_config_backup_destination_details_remote_region}
        type: ${var.distributed_autonomous_database_db_backup_config_backup_destination_details_type}
        vpcPasswordSecretRef:
          key: example-key
          name: example-secret
          namespace: upbound-system
        vpcUser: ${var.distributed_autonomous_database_db_backup_config_backup_destination_details_vpc_user}
      recoveryWindowInDays: ${var.distributed_autonomous_database_db_backup_config_recovery_window_in_days}
    dbDeploymentType: ${var.distributed_autonomous_database_db_deployment_type}
    dbWorkload: ${var.distributed_autonomous_database_db_workload}
    definedTags:
      foo-namespace.bar-key: value
    displayName: ${var.distributed_autonomous_database_display_name}
    distributed_autonomous_database_id: ${var.distributed_autonomous_database_distributed_autonomous_database_id}
    freeformTags:
      bar-key: value
    listenerPort: ${var.distributed_autonomous_database_listener_port}
    listenerPortTls: ${var.distributed_autonomous_database_listener_port_tls}
    ncharacterSet: ${var.distributed_autonomous_database_ncharacter_set}
    onsPortLocal: ${var.distributed_autonomous_database_ons_port_local}
    onsPortRemote: ${var.distributed_autonomous_database_ons_port_remote}
    patchOperations:
    - operation: ${var.distributed_autonomous_database_patch_operations_operation}
      selection: ${var.distributed_autonomous_database_patch_operations_selection}
      value: ${var.distributed_autonomous_database_patch_operations_value}
    prefix: ${var.distributed_autonomous_database_prefix}
    privateEndpointIds: ${var.distributed_autonomous_database_private_endpoint_ids}
    replicationFactor: ${var.distributed_autonomous_database_replication_factor}
    replicationMethod: ${var.distributed_autonomous_database_replication_method}
    replicationUnit: ${var.distributed_autonomous_database_replication_unit}
    shardDetails:
    - adminPasswordSecretRef:
        key: example-key
        name: example-secret
        namespace: upbound-system
      cloudAutonomousVmClusterIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
      computeCount: ${var.distributed_autonomous_database_shard_details_compute_count}
      dataStorageSizeInGbs: ${var.distributed_autonomous_database_shard_details_data_storage_size_in_gbs}
      isAutoScalingEnabled: ${var.distributed_autonomous_database_shard_details_is_auto_scaling_enabled}
      kmsKeyIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key
      kmsKeyVersionIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_key_version
      peerCloudAutonomousVmClusterIds: ${var.distributed_autonomous_database_shard_details_peer_cloud_autonomous_vm_cluster_ids}
      peerDetails:
      - cloudAutonomousVmClusterIdSelector:
          matchLabels:
            testing.upbound.io/example-name: test_cloud_autonomous_vm_cluster
        fastStartFailOverLagLimitInSeconds: ${var.distributed_autonomous_database_shard_details_peer_details_fast_start_fail_over_lag_limit_in_seconds}
        isAutomaticFailoverEnabled: ${var.distributed_autonomous_database_shard_details_peer_details_is_automatic_failover_enabled}
        protectionMode: ${var.distributed_autonomous_database_shard_details_peer_details_protection_mode}
        standbyMaintenanceBufferInDays: ${var.distributed_autonomous_database_shard_details_peer_details_standby_maintenance_buffer_in_days}
      shardSpace: ${var.distributed_autonomous_database_shard_details_shard_space}
      source: ${var.distributed_autonomous_database_shard_details_source}
      vaultIdSelector:
        matchLabels:
          testing.upbound.io/example-name: test_vault
    shardingMethod: ${var.distributed_autonomous_database_sharding_method}
