---
apiVersion: queue.oci.m.upbound.io/v1alpha1
kind: Queue
metadata:
  labels:
    testing.upbound.io/example-name: queue_label_1
  name: queue1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: queue1
