apiVersion: queue.oci.m.upbound.io/v1alpha1
kind: Queue
metadata:
  namespace: crossplane-system
  name: queue1
  labels:
    testing.upbound.io/example-name: queue_label_1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: "queue1"