---
apiVersion: bastion.oci.m.upbound.io/v1alpha1
kind: Bastion
metadata:
  labels:
    testing.upbound.io/example-name: bastion_label_1
  name: bastion1
  namespace: crossplane-system
spec:
  forProvider:
    bastionType: STANDARD
    clientCidrBlockAllowList:
    - 0.0.0.0/0
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    name: bastion1
    targetSubnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_label_1
