---
apiVersion: budget.oci.m.upbound.io/v1alpha1
kind: AlertRule
metadata:
  labels:
    testing.upbound.io/example-name: alertrule_label_1
  name: alertrule1
  namespace: crossplane-system
spec:
  forProvider:
    budgetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: budget_label_1
    threshold: 90.0
    thresholdType: PERCENTAGE
    type: ACTUAL
