---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: Key
metadata:
  labels:
    testing.upbound.io/example-name: key_label_2
  name: key2
  namespace: crossplane-system
spec:
  forProvider:
    compartmentId: ${COMPARTMENT_OCID}
    displayName: key2
    keyShape:
    - algorithm: RSA
      length: 256
    managementEndpoint: ${VAULT_MANAGEMENT_ENDPOINT}
