---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: EncryptedData
metadata:
  labels:
    testing.upbound.io/example-name: encrypteddata_label_1
  name: encrypteddata1
  namespace: crossplane-system
spec:
  forProvider:
    cryptoEndpoint: ${VAULT_CRYPTO_ENDPOINT}
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: key_label_1
    plaintext: UGxhaW4gdGV4dCBmb3IgZW5jcnlwdGlvbg==
