---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: GeneratedKey
metadata:
  labels:
    testing.upbound.io/example-name: generatedkey_label_1
  name: generatedkey1
  namespace: crossplane-system
spec:
  forProvider:
    cryptoEndpoint: ${VAULT_CRYPTO_ENDPOINT}
    includePlaintextKey: true
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: key_label_1
    keyShape:
    - algorithm: AES
      length: 32
