---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: Key
metadata:
  labels:
    testing.upbound.io/example-name: key_label_1
  name: key1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentId: ${COMPARTMENT_OCID}
    displayName: key1
    keyShape:
    - algorithm: AES
      length: 32
    managementEndpoint: ${VAULT_MANAGEMENT_ENDPOINT}
