---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: KeyVersion
metadata:
  labels:
    testing.upbound.io/example-name: keyversion_label_1
  name: keyversion1
  namespace: crossplane-system
spec:
  forProvider:
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: key_label_1
    managementEndpoint: ${VAULT_MANAGEMENT_ENDPOINT}
