---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: Sign
metadata:
  labels:
    testing.upbound.io/example-name: sign_label_1
  name: sign1
  namespace: crossplane-system
spec:
  forProvider:
    cryptoEndpoint: ${VAULT_CRYPTO_ENDPOINT}
    keyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: key_label_2
    message: bWVzc2FnZQ==
    signingAlgorithm: SHA_256_RSA_PKCS1_V1_5
