---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: VaultReplication
metadata:
  labels:
    testing.upbound.io/example-name: vaultreplication_label_1
  name: vaultreplication1
  namespace: crossplane-system
spec:
  forProvider:
    replicaRegion: us-phoenix-1
    vaultIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vault_label_2
