---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: Vault
metadata:
  labels:
    testing.upbound.io/example-name: vault_label_1
  name: vault1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: vault1
    vaultType: DEFAULT
