---
apiVersion: kms.oci.m.upbound.io/v1alpha1
kind: Vault
metadata:
  labels:
    testing.upbound.io/example-name: vault_label_2
  name: vault2
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: vault2
    vaultType: VIRTUAL_PRIVATE
