apiVersion: budget.oci.m.upbound.io/v1alpha1
kind: CostAnomalyEvent
metadata:
  annotations:
    meta.upbound.io/example-id: budget/v1alpha1/costanomalyevent
  labels:
    testing.upbound.io/example-name: test_cost_anomaly_event
  name: test-cost-anomaly-event
  namespace: upbound-system
spec:
  forProvider:
    costAnomalyEventIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cost_anomaly_event
    definedTags:
      Operations.CostCenter: "42"
    feedbackResponse: ${var.cost_anomaly_event_feedback_response}
    freeformTags:
      Department: Finance
