---
apiVersion: psql.oci.m.upbound.io/v1alpha1
kind: PsqlDbSystem
metadata:
  labels:
    testing.upbound.io/example-name: psqldbsystem_label_1
  name: psqldbsystem1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    credentials:
    - passwordDetails:
      - passwordSecretRef:
          key: credentials
          name: password-secret-psqldbsystem1
          namespace: crossplane-system
        passwordTypeSecretRef:
          key: credentials
          name: password-type-secret-psqldbsystem1
          namespace: crossplane-system
      username: adminUser
    dbVersion: '14'
    displayName: psqldbsystem1
    instanceMemorySizeInGbs: 16
    instanceOcpuCount: 1
    networkDetails:
    - isReaderEndpointEnabled: true
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: subnet_label_2
    shape: PostgreSQL.VM.Standard.E5.Flex
    storageDetails:
    - isRegionallyDurable: true
      systemType: OCI_OPTIMIZED_STORAGE
    systemType: OCI_OPTIMIZED_STORAGE
