/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha1 "github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1"
	v1alpha11 "github.com/oracle/provider-oci/apis/cluster/logging/v1alpha1"
	v1alpha12 "github.com/oracle/provider-oci/apis/cluster/objectstorage/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this Fleet.
func (mg *Fleet) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.InventoryLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.InventoryLog[i3].LogGroupID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.InventoryLog[i3].LogGroupIDRef,
			Selector:     mg.Spec.ForProvider.InventoryLog[i3].LogGroupIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogGroupList{},
				Managed: &v1alpha11.LogGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.InventoryLog[i3].LogGroupID")
		}
		mg.Spec.ForProvider.InventoryLog[i3].LogGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.InventoryLog[i3].LogGroupIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.InventoryLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.InventoryLog[i3].LogID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.InventoryLog[i3].LogIDRef,
			Selector:     mg.Spec.ForProvider.InventoryLog[i3].LogIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogList{},
				Managed: &v1alpha11.Log{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.InventoryLog[i3].LogID")
		}
		mg.Spec.ForProvider.InventoryLog[i3].LogID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.InventoryLog[i3].LogIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.OperationLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OperationLog[i3].LogGroupID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OperationLog[i3].LogGroupIDRef,
			Selector:     mg.Spec.ForProvider.OperationLog[i3].LogGroupIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogGroupList{},
				Managed: &v1alpha11.LogGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.OperationLog[i3].LogGroupID")
		}
		mg.Spec.ForProvider.OperationLog[i3].LogGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.OperationLog[i3].LogGroupIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.OperationLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.OperationLog[i3].LogID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.OperationLog[i3].LogIDRef,
			Selector:     mg.Spec.ForProvider.OperationLog[i3].LogIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogList{},
				Managed: &v1alpha11.Log{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.OperationLog[i3].LogID")
		}
		mg.Spec.ForProvider.OperationLog[i3].LogID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.OperationLog[i3].LogIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.InventoryLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.InventoryLog[i3].LogGroupID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.InventoryLog[i3].LogGroupIDRef,
			Selector:     mg.Spec.InitProvider.InventoryLog[i3].LogGroupIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogGroupList{},
				Managed: &v1alpha11.LogGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.InventoryLog[i3].LogGroupID")
		}
		mg.Spec.InitProvider.InventoryLog[i3].LogGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.InventoryLog[i3].LogGroupIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.InventoryLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.InventoryLog[i3].LogID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.InventoryLog[i3].LogIDRef,
			Selector:     mg.Spec.InitProvider.InventoryLog[i3].LogIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogList{},
				Managed: &v1alpha11.Log{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.InventoryLog[i3].LogID")
		}
		mg.Spec.InitProvider.InventoryLog[i3].LogID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.InventoryLog[i3].LogIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.OperationLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OperationLog[i3].LogGroupID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OperationLog[i3].LogGroupIDRef,
			Selector:     mg.Spec.InitProvider.OperationLog[i3].LogGroupIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogGroupList{},
				Managed: &v1alpha11.LogGroup{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.OperationLog[i3].LogGroupID")
		}
		mg.Spec.InitProvider.OperationLog[i3].LogGroupID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.OperationLog[i3].LogGroupIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.OperationLog); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.OperationLog[i3].LogID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.OperationLog[i3].LogIDRef,
			Selector:     mg.Spec.InitProvider.OperationLog[i3].LogIDSelector,
			To: reference.To{
				List:    &v1alpha11.LogList{},
				Managed: &v1alpha11.Log{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.OperationLog[i3].LogID")
		}
		mg.Spec.InitProvider.OperationLog[i3].LogID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.OperationLog[i3].LogIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this FleetAdvancedFeatureConfiguration.
func (mg *FleetAdvancedFeatureConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AnalyticBucketName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AnalyticBucketNameRef,
		Selector:     mg.Spec.ForProvider.AnalyticBucketNameSelector,
		To: reference.To{
			List:    &v1alpha12.BucketList{},
			Managed: &v1alpha12.Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AnalyticBucketName")
	}
	mg.Spec.ForProvider.AnalyticBucketName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AnalyticBucketNameRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.CryptoEventAnalysis); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupIDRef,
				Selector:     mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupIDSelector,
				To: reference.To{
					List:    &v1alpha11.LogGroupList{},
					Managed: &v1alpha11.LogGroup{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupID")
			}
			mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.CryptoEventAnalysis); i3++ {
		for i4 := 0; i4 < len(mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogIDRef,
				Selector:     mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogIDSelector,
				To: reference.To{
					List:    &v1alpha11.LogList{},
					Managed: &v1alpha11.Log{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogID")
			}
			mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.ForProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogIDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FleetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FleetIDRef,
		Selector:     mg.Spec.ForProvider.FleetIDSelector,
		To: reference.To{
			List:    &FleetList{},
			Managed: &Fleet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FleetID")
	}
	mg.Spec.ForProvider.FleetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FleetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AnalyticBucketName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AnalyticBucketNameRef,
		Selector:     mg.Spec.InitProvider.AnalyticBucketNameSelector,
		To: reference.To{
			List:    &v1alpha12.BucketList{},
			Managed: &v1alpha12.Bucket{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AnalyticBucketName")
	}
	mg.Spec.InitProvider.AnalyticBucketName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AnalyticBucketNameRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.CryptoEventAnalysis); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupIDRef,
				Selector:     mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupIDSelector,
				To: reference.To{
					List:    &v1alpha11.LogGroupList{},
					Managed: &v1alpha11.LogGroup{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupID")
			}
			mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogGroupIDRef = rsp.ResolvedReference

		}
	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.CryptoEventAnalysis); i3++ {
		for i4 := 0; i4 < len(mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog); i4++ {
			rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
				CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogID),
				Extract:      resource.ExtractResourceID(),
				Namespace:    mg.GetNamespace(),
				Reference:    mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogIDRef,
				Selector:     mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogIDSelector,
				To: reference.To{
					List:    &v1alpha11.LogList{},
					Managed: &v1alpha11.Log{},
				},
			})
			if err != nil {
				return errors.Wrap(err, "mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogID")
			}
			mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogID = reference.ToPtrValue(rsp.ResolvedValue)
			mg.Spec.InitProvider.CryptoEventAnalysis[i3].SummarizedEventsLog[i4].LogIDRef = rsp.ResolvedReference

		}
	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FleetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FleetIDRef,
		Selector:     mg.Spec.InitProvider.FleetIDSelector,
		To: reference.To{
			List:    &FleetList{},
			Managed: &Fleet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FleetID")
	}
	mg.Spec.InitProvider.FleetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FleetIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this FleetAgentConfiguration.
func (mg *FleetAgentConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FleetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FleetIDRef,
		Selector:     mg.Spec.ForProvider.FleetIDSelector,
		To: reference.To{
			List:    &FleetList{},
			Managed: &Fleet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FleetID")
	}
	mg.Spec.ForProvider.FleetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FleetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FleetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FleetIDRef,
		Selector:     mg.Spec.InitProvider.FleetIDSelector,
		To: reference.To{
			List:    &FleetList{},
			Managed: &Fleet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FleetID")
	}
	mg.Spec.InitProvider.FleetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FleetIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this JmsPlugin.
func (mg *JmsPlugin) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.FleetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.FleetIDRef,
		Selector:     mg.Spec.ForProvider.FleetIDSelector,
		To: reference.To{
			List:    &FleetList{},
			Managed: &Fleet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.FleetID")
	}
	mg.Spec.ForProvider.FleetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.FleetIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.FleetID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.FleetIDRef,
		Selector:     mg.Spec.InitProvider.FleetIDSelector,
		To: reference.To{
			List:    &FleetList{},
			Managed: &Fleet{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.FleetID")
	}
	mg.Spec.InitProvider.FleetID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.FleetIDRef = rsp.ResolvedReference

	return nil
}
