---
apiVersion: loadbalancer.oci.m.upbound.io/v1alpha1
kind: RoutingPolicy
metadata:
  labels:
    testing.upbound.io/example-name: routingpolicy_label_1
  name: routingpolicy1
  namespace: crossplane-system
spec:
  forProvider:
    conditionLanguageVersion: V1
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: loadbalancer_label_1
    name: routingpolicy1
    rules:
    - actions:
      - backendSetNameSelector:
          matchLabels:
            testing.upbound.io/example-name: backendset_label_1
        name: FORWARD_TO_BACKENDSET
      condition: all(http.request.url.path eq (i ''))
      name: example_routing_rules
