---
apiVersion: loadbalancer.oci.m.upbound.io/v1alpha1
kind: SSLCipherSuite
metadata:
  labels:
    testing.upbound.io/example-name: sslciphersuite_label_1
  name: sslciphersuite1
  namespace: crossplane-system
spec:
  forProvider:
    ciphers:
    - AES128-SHA
    - AES256-SHA
    loadBalancerIdSelector:
      matchLabels:
        testing.upbound.io/example-name: loadbalancer_label_1
    name: sslciphersuite1
