apiVersion: integration.oci.m.upbound.io/v1alpha1
kind: IntegrationInstance
metadata:
  namespace: crossplane-system
  labels:
    testing.upbound.io/example-name: integrationinstance_label_1
  name: integrationinstance1
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: integrationinstance1
    integrationInstanceType: "STANDARDX"
    isByol: False
    messagePacks: 1
