---
apiVersion: containerengine.oci.m.upbound.io/v1alpha1
kind: Cluster
metadata:
  labels:
    testing.upbound.io/example-name: cluster_label_1
  name: cluster1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    kubernetesVersion: v1.34.1
    name: cluster1
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn_label_1
