---
apiVersion: containerengine.oci.m.upbound.io/v1alpha1
kind: Cluster
metadata:
  labels:
    testing.upbound.io/example-name: cluster_label_2
  name: cluster2
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    endpointConfig:
    - isPublicIpEnabled: false
      subnetIdSelector:
        matchLabels:
          testing.upbound.io/example-name: subnet_label_1
    kubernetesVersion: v1.34.1
    name: cluster2
    type: BASIC_CLUSTER
    vcnIdSelector:
      matchLabels:
        testing.upbound.io/example-name: vcn_label_1
