/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ManagementCloudExadataStorageServerConnectorInitParameters struct {
}

type ManagementCloudExadataStorageServerConnectorObservation struct {

	// The additional details of the resource defined in {"key": "value"} format. Example: {"bar-key": "value"}
	// +mapType=granular
	AdditionalDetails map[string]*string `json:"additionalDetails,omitempty" tf:"additional_details,omitempty"`

	// The OCID of the agent for the Exadata storage server.
	AgentID *string `json:"agentId,omitempty" tf:"agent_id,omitempty"`

	// The unique string of the connection. For example, "https:///MS/RESTService/".
	ConnectionURI *string `json:"connectionUri,omitempty" tf:"connection_uri,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The name of the Exadata resource. English letters, numbers, "-", "_" and "." only.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the Exadata resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The internal ID of the Exadata resource.
	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// The details of the lifecycle state of the Exadata resource.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The type of Exadata resource.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The current lifecycle state of the database resource.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The status of the Exadata resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The OCID of the Exadata storage server.
	StorageServerID *string `json:"storageServerId,omitempty" tf:"storage_server_id,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. System tags can be viewed by users, but can only be created by the system.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The timestamp of the creation of the Exadata resource.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The timestamp of the last update of the Exadata resource.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The version of the Exadata resource.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ManagementCloudExadataStorageServerConnectorParameters struct {
}

type ManagementCloudExadataStorageServerInitParameters struct {

	// The OCID of the Exadata storage server.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ManagementCloudExadataStorageServer
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	CloudExadataStorageServerID *string `json:"cloudExadataStorageServerId,omitempty" tf:"cloud_exadata_storage_server_id,omitempty"`

	// Reference to a ManagementCloudExadataStorageServer in database to populate cloudExadataStorageServerId.
	// +kubebuilder:validation:Optional
	CloudExadataStorageServerIDRef *v1.NamespacedReference `json:"cloudExadataStorageServerIdRef,omitempty" tf:"-"`

	// Selector for a ManagementCloudExadataStorageServer in database to populate cloudExadataStorageServerId.
	// +kubebuilder:validation:Optional
	CloudExadataStorageServerIDSelector *v1.NamespacedSelector `json:"cloudExadataStorageServerIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

type ManagementCloudExadataStorageServerObservation struct {

	// The additional details of the resource defined in {"key": "value"} format. Example: {"bar-key": "value"}
	// +mapType=granular
	AdditionalDetails map[string]*string `json:"additionalDetails,omitempty" tf:"additional_details,omitempty"`

	// The CPU count of the Exadata storage server.
	CPUCount *float64 `json:"cpuCount,omitempty" tf:"cpu_count,omitempty"`

	// The OCID of the Exadata storage server.
	CloudExadataStorageServerID *string `json:"cloudExadataStorageServerId,omitempty" tf:"cloud_exadata_storage_server_id,omitempty"`

	// The connector of the Exadata storage server.
	Connector []ManagementCloudExadataStorageServerConnectorObservation `json:"connector,omitempty" tf:"connector,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// The name of the Exadata resource. English letters, numbers, "-", "_" and "." only.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// The OCID of the Exadata infrastructure.
	ExadataInfrastructureID *string `json:"exadataInfrastructureId,omitempty" tf:"exadata_infrastructure_id,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// The OCID of the Exadata resource.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// The IP address of the Exadata storage server.
	IPAddress *string `json:"ipAddress,omitempty" tf:"ip_address,omitempty"`

	// The internal ID of the Exadata resource.
	InternalID *string `json:"internalId,omitempty" tf:"internal_id,omitempty"`

	// The details of the lifecycle state of the Exadata resource.
	LifecycleDetails *string `json:"lifecycleDetails,omitempty" tf:"lifecycle_details,omitempty"`

	// The make model of the Exadata storage server.
	MakeModel *string `json:"makeModel,omitempty" tf:"make_model,omitempty"`

	// The maximum flash disk IO operations per second of the Exadata storage server.
	MaxFlashDiskIops *float64 `json:"maxFlashDiskIops,omitempty" tf:"max_flash_disk_iops,omitempty"`

	// The maximum flash disk IO throughput in MB/s of the Exadata storage server.
	MaxFlashDiskThroughput *float64 `json:"maxFlashDiskThroughput,omitempty" tf:"max_flash_disk_throughput,omitempty"`

	// The maximum hard disk IO operations per second of the Exadata storage server.
	MaxHardDiskIops *float64 `json:"maxHardDiskIops,omitempty" tf:"max_hard_disk_iops,omitempty"`

	// The maximum hard disk IO throughput in MB/s of the Exadata storage server.
	MaxHardDiskThroughput *float64 `json:"maxHardDiskThroughput,omitempty" tf:"max_hard_disk_throughput,omitempty"`

	// The Exadata storage server memory size in GB.
	MemoryGb *float64 `json:"memoryGb,omitempty" tf:"memory_gb,omitempty"`

	// The type of Exadata resource.
	ResourceType *string `json:"resourceType,omitempty" tf:"resource_type,omitempty"`

	// The current lifecycle state of the database resource.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// The status of the Exadata resource.
	Status *string `json:"status,omitempty" tf:"status,omitempty"`

	// The OCID of the Exadata storage server grid.
	StorageGridID *string `json:"storageGridId,omitempty" tf:"storage_grid_id,omitempty"`

	// System tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. System tags can be viewed by users, but can only be created by the system.  Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// The timestamp of the creation of the Exadata resource.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// The timestamp of the last update of the Exadata resource.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`

	// The version of the Exadata resource.
	Version *string `json:"version,omitempty" tf:"version,omitempty"`
}

type ManagementCloudExadataStorageServerParameters struct {

	// The OCID of the Exadata storage server.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.ManagementCloudExadataStorageServer
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	CloudExadataStorageServerID *string `json:"cloudExadataStorageServerId,omitempty" tf:"cloud_exadata_storage_server_id,omitempty"`

	// Reference to a ManagementCloudExadataStorageServer in database to populate cloudExadataStorageServerId.
	// +kubebuilder:validation:Optional
	CloudExadataStorageServerIDRef *v1.NamespacedReference `json:"cloudExadataStorageServerIdRef,omitempty" tf:"-"`

	// Selector for a ManagementCloudExadataStorageServer in database to populate cloudExadataStorageServerId.
	// +kubebuilder:validation:Optional
	CloudExadataStorageServerIDSelector *v1.NamespacedSelector `json:"cloudExadataStorageServerIdSelector,omitempty" tf:"-"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. For more information, see Resource Tags. Example: {"Operations.CostCenter": "42"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace. For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`
}

// ManagementCloudExadataStorageServerSpec defines the desired state of ManagementCloudExadataStorageServer
type ManagementCloudExadataStorageServerSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            ManagementCloudExadataStorageServerParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider ManagementCloudExadataStorageServerInitParameters `json:"initProvider,omitempty"`
}

// ManagementCloudExadataStorageServerStatus defines the observed state of ManagementCloudExadataStorageServer.
type ManagementCloudExadataStorageServerStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        ManagementCloudExadataStorageServerObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// ManagementCloudExadataStorageServer is the Schema for the ManagementCloudExadataStorageServers API. Provides the Cloud Exadata Storage Server resource in Oracle Cloud Infrastructure Database Management service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type ManagementCloudExadataStorageServer struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	Spec              ManagementCloudExadataStorageServerSpec   `json:"spec"`
	Status            ManagementCloudExadataStorageServerStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// ManagementCloudExadataStorageServerList contains a list of ManagementCloudExadataStorageServers
type ManagementCloudExadataStorageServerList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []ManagementCloudExadataStorageServer `json:"items"`
}

// Repository type metadata.
var (
	ManagementCloudExadataStorageServer_Kind             = "ManagementCloudExadataStorageServer"
	ManagementCloudExadataStorageServer_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: ManagementCloudExadataStorageServer_Kind}.String()
	ManagementCloudExadataStorageServer_KindAPIVersion   = ManagementCloudExadataStorageServer_Kind + "." + CRDGroupVersion.String()
	ManagementCloudExadataStorageServer_GroupVersionKind = CRDGroupVersion.WithKind(ManagementCloudExadataStorageServer_Kind)
)

func init() {
	SchemeBuilder.Register(&ManagementCloudExadataStorageServer{}, &ManagementCloudExadataStorageServerList{})
}
