/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ItemsInitParameters struct {

	// The property name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The property value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ItemsObservation struct {

	// The property name.
	Name *string `json:"name,omitempty" tf:"name,omitempty"`

	// The property value.
	Value *string `json:"value,omitempty" tf:"value,omitempty"`
}

type ItemsParameters struct {

	// The property name.
	// +kubebuilder:validation:Optional
	Name *string `json:"name" tf:"name,omitempty"`

	// The property value.
	// +kubebuilder:validation:Optional
	Value *string `json:"value" tf:"value,omitempty"`
}

type MigrationAssessmentAssessorActionInitParameters struct {

	// The OCID of the Assessment
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.MigrationAssessment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	AssessmentID *string `json:"assessmentId,omitempty" tf:"assessment_id,omitempty"`

	// Reference to a MigrationAssessment in database to populate assessmentId.
	// +kubebuilder:validation:Optional
	AssessmentIDRef *v1.NamespacedReference `json:"assessmentIdRef,omitempty" tf:"-"`

	// Selector for a MigrationAssessment in database to populate assessmentId.
	// +kubebuilder:validation:Optional
	AssessmentIDSelector *v1.NamespacedSelector `json:"assessmentIdSelector,omitempty" tf:"-"`

	// The Accessor Action
	AssessorAction *string `json:"assessorAction,omitempty" tf:"assessor_action,omitempty"`

	// The name of the Assessor
	AssessorName *string `json:"assessorName,omitempty" tf:"assessor_name,omitempty"`

	// Array of name-value details for assessor action.
	Items []ItemsInitParameters `json:"items,omitempty" tf:"items,omitempty"`
}

type MigrationAssessmentAssessorActionObservation struct {

	// The OCID of the Assessment
	AssessmentID *string `json:"assessmentId,omitempty" tf:"assessment_id,omitempty"`

	// The Accessor Action
	AssessorAction *string `json:"assessorAction,omitempty" tf:"assessor_action,omitempty"`

	// The name of the Assessor
	AssessorName *string `json:"assessorName,omitempty" tf:"assessor_name,omitempty"`

	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Array of name-value details for assessor action.
	Items []ItemsObservation `json:"items,omitempty" tf:"items,omitempty"`
}

type MigrationAssessmentAssessorActionParameters struct {

	// The OCID of the Assessment
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1.MigrationAssessment
	// +crossplane:generate:reference:extractor=github.com/crossplane/upjet/v2/pkg/resource.ExtractResourceID()
	// +kubebuilder:validation:Optional
	AssessmentID *string `json:"assessmentId,omitempty" tf:"assessment_id,omitempty"`

	// Reference to a MigrationAssessment in database to populate assessmentId.
	// +kubebuilder:validation:Optional
	AssessmentIDRef *v1.NamespacedReference `json:"assessmentIdRef,omitempty" tf:"-"`

	// Selector for a MigrationAssessment in database to populate assessmentId.
	// +kubebuilder:validation:Optional
	AssessmentIDSelector *v1.NamespacedSelector `json:"assessmentIdSelector,omitempty" tf:"-"`

	// The Accessor Action
	// +kubebuilder:validation:Optional
	AssessorAction *string `json:"assessorAction,omitempty" tf:"assessor_action,omitempty"`

	// The name of the Assessor
	// +kubebuilder:validation:Optional
	AssessorName *string `json:"assessorName,omitempty" tf:"assessor_name,omitempty"`

	// Array of name-value details for assessor action.
	// +kubebuilder:validation:Optional
	Items []ItemsParameters `json:"items,omitempty" tf:"items,omitempty"`
}

// MigrationAssessmentAssessorActionSpec defines the desired state of MigrationAssessmentAssessorAction
type MigrationAssessmentAssessorActionSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MigrationAssessmentAssessorActionParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MigrationAssessmentAssessorActionInitParameters `json:"initProvider,omitempty"`
}

// MigrationAssessmentAssessorActionStatus defines the observed state of MigrationAssessmentAssessorAction.
type MigrationAssessmentAssessorActionStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MigrationAssessmentAssessorActionObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MigrationAssessmentAssessorAction is the Schema for the MigrationAssessmentAssessorActions API. Provides the Assessment Assessor Action resource in Oracle Cloud Infrastructure Database Migration service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type MigrationAssessmentAssessorAction struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.assessorAction) || (has(self.initProvider) && has(self.initProvider.assessorAction))",message="spec.forProvider.assessorAction is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.assessorName) || (has(self.initProvider) && has(self.initProvider.assessorName))",message="spec.forProvider.assessorName is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.items) || (has(self.initProvider) && has(self.initProvider.items))",message="spec.forProvider.items is a required parameter"
	Spec   MigrationAssessmentAssessorActionSpec   `json:"spec"`
	Status MigrationAssessmentAssessorActionStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MigrationAssessmentAssessorActionList contains a list of MigrationAssessmentAssessorActions
type MigrationAssessmentAssessorActionList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MigrationAssessmentAssessorAction `json:"items"`
}

// Repository type metadata.
var (
	MigrationAssessmentAssessorAction_Kind             = "MigrationAssessmentAssessorAction"
	MigrationAssessmentAssessorAction_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MigrationAssessmentAssessorAction_Kind}.String()
	MigrationAssessmentAssessorAction_KindAPIVersion   = MigrationAssessmentAssessorAction_Kind + "." + CRDGroupVersion.String()
	MigrationAssessmentAssessorAction_GroupVersionKind = CRDGroupVersion.WithKind(MigrationAssessmentAssessorAction_Kind)
)

func init() {
	SchemeBuilder.Register(&MigrationAssessmentAssessorAction{}, &MigrationAssessmentAssessorActionList{})
}
