/*
Copyright 2022 Upbound Inc.
*/

// Code generated by upjet. DO NOT EDIT.

package v1alpha1

import (
	metav1 "k8s.io/apimachinery/pkg/apis/meta/v1"
	"k8s.io/apimachinery/pkg/runtime/schema"

	v1 "github.com/crossplane/crossplane-runtime/v2/apis/common/v1"
	v2 "github.com/crossplane/crossplane-runtime/v2/apis/common/v2"
)

type ExcludeObjectsInitParameters struct {

	// (Applicable when database_combination=ORACLE) Whether an excluded table should be omitted from replication. Only valid for database objects  that have are of type TABLE and object status EXCLUDE.
	IsOmitExcludedTableFromReplication *bool `json:"isOmitExcludedTableFromReplication,omitempty" tf:"is_omit_excluded_table_from_replication,omitempty"`

	// Name of the object (regular expression is allowed)
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// Owner of the object (regular expression is allowed)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Schema of the object (regular expression is allowed)
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Type of object to exclude. If not specified, matching owners and object names of type TABLE would be excluded.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ExcludeObjectsObservation struct {

	// (Applicable when database_combination=ORACLE) Whether an excluded table should be omitted from replication. Only valid for database objects  that have are of type TABLE and object status EXCLUDE.
	IsOmitExcludedTableFromReplication *bool `json:"isOmitExcludedTableFromReplication,omitempty" tf:"is_omit_excluded_table_from_replication,omitempty"`

	// Name of the object (regular expression is allowed)
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// Owner of the object (regular expression is allowed)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Schema of the object (regular expression is allowed)
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Type of object to exclude. If not specified, matching owners and object names of type TABLE would be excluded.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type ExcludeObjectsParameters struct {

	// (Applicable when database_combination=ORACLE) Whether an excluded table should be omitted from replication. Only valid for database objects  that have are of type TABLE and object status EXCLUDE.
	// +kubebuilder:validation:Optional
	IsOmitExcludedTableFromReplication *bool `json:"isOmitExcludedTableFromReplication,omitempty" tf:"is_omit_excluded_table_from_replication,omitempty"`

	// Name of the object (regular expression is allowed)
	// +kubebuilder:validation:Optional
	Object *string `json:"object" tf:"object,omitempty"`

	// Owner of the object (regular expression is allowed)
	// +kubebuilder:validation:Optional
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Schema of the object (regular expression is allowed)
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Type of object to exclude. If not specified, matching owners and object names of type TABLE would be excluded.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IncludeObjectsInitParameters struct {

	// (Applicable when database_combination=ORACLE) Whether an excluded table should be omitted from replication. Only valid for database objects  that have are of type TABLE and object status EXCLUDE.
	IsOmitExcludedTableFromReplication *bool `json:"isOmitExcludedTableFromReplication,omitempty" tf:"is_omit_excluded_table_from_replication,omitempty"`

	// Name of the object (regular expression is allowed)
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// Owner of the object (regular expression is allowed)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Schema of the object (regular expression is allowed)
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Type of object to exclude. If not specified, matching owners and object names of type TABLE would be excluded.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IncludeObjectsObservation struct {

	// (Applicable when database_combination=ORACLE) Whether an excluded table should be omitted from replication. Only valid for database objects  that have are of type TABLE and object status EXCLUDE.
	IsOmitExcludedTableFromReplication *bool `json:"isOmitExcludedTableFromReplication,omitempty" tf:"is_omit_excluded_table_from_replication,omitempty"`

	// Name of the object (regular expression is allowed)
	Object *string `json:"object,omitempty" tf:"object,omitempty"`

	// Owner of the object (regular expression is allowed)
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Schema of the object (regular expression is allowed)
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Type of object to exclude. If not specified, matching owners and object names of type TABLE would be excluded.
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type IncludeObjectsParameters struct {

	// (Applicable when database_combination=ORACLE) Whether an excluded table should be omitted from replication. Only valid for database objects  that have are of type TABLE and object status EXCLUDE.
	// +kubebuilder:validation:Optional
	IsOmitExcludedTableFromReplication *bool `json:"isOmitExcludedTableFromReplication,omitempty" tf:"is_omit_excluded_table_from_replication,omitempty"`

	// Name of the object (regular expression is allowed)
	// +kubebuilder:validation:Optional
	Object *string `json:"object" tf:"object,omitempty"`

	// Owner of the object (regular expression is allowed)
	// +kubebuilder:validation:Optional
	Owner *string `json:"owner,omitempty" tf:"owner,omitempty"`

	// Schema of the object (regular expression is allowed)
	// +kubebuilder:validation:Optional
	Schema *string `json:"schema,omitempty" tf:"schema,omitempty"`

	// Type of object to exclude. If not specified, matching owners and object names of type TABLE would be excluded.
	// +kubebuilder:validation:Optional
	Type *string `json:"type,omitempty" tf:"type,omitempty"`
}

type MigrationAssessmentInitParameters struct {

	// (Updatable) Time allowed for the application downtime.
	AcceptableDowntime *string `json:"acceptableDowntime,omitempty" tf:"acceptable_downtime,omitempty"`

	// Specifies the database objects to be excluded from the migration in bulk. The definition accepts input in a CSV format, newline separated for each entry. More details can be found in the documentation.
	BulkIncludeExcludeData *string `json:"bulkIncludeExcludeData,omitempty" tf:"bulk_include_exclude_data,omitempty"`

	// (Updatable) The OCID of the resource being referenced.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of assessment creation.
	CreationType *string `json:"creationType,omitempty" tf:"creation_type,omitempty"`

	// (Updatable) The combination of source and target databases participating in a migration. Example: ORACLE means the migration is meant for migrating Oracle source and target databases.
	DatabaseCombination *string `json:"databaseCombination,omitempty" tf:"database_combination,omitempty"`

	// (Updatable) The size of a source database.
	DatabaseDataSize *string `json:"databaseDataSize,omitempty" tf:"database_data_size,omitempty"`

	// (Updatable) DDL expectation values.
	DdlExpectation *string `json:"ddlExpectation,omitempty" tf:"ddl_expectation,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly description. Does not have to be unique, and it's changeable.  Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable.  Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Database objects to exclude from migration, cannot be specified alongside 'includeObjects'
	ExcludeObjects []ExcludeObjectsInitParameters `json:"excludeObjects,omitempty" tf:"exclude_objects,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.  For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Database objects to include from migration, cannot be specified alongside 'excludeObjects'
	IncludeObjects []IncludeObjectsInitParameters `json:"includeObjects,omitempty" tf:"include_objects,omitempty"`

	// (Updatable) A network speed in Megabits per second.
	NetworkSpeedMegabitPerSecond *string `json:"networkSpeedMegabitPerSecond,omitempty" tf:"network_speed_megabit_per_second,omitempty"`

	// (Updatable) Source Assessment Connection object
	SourceDatabaseConnection []SourceDatabaseConnectionInitParameters `json:"sourceDatabaseConnection,omitempty" tf:"source_database_connection,omitempty"`

	// (Updatable) Target Assessment Connection object
	TargetDatabaseConnection []TargetDatabaseConnectionInitParameters `json:"targetDatabaseConnection,omitempty" tf:"target_database_connection,omitempty"`
}

type MigrationAssessmentObservation struct {

	// (Updatable) Time allowed for the application downtime.
	AcceptableDowntime *string `json:"acceptableDowntime,omitempty" tf:"acceptable_downtime,omitempty"`

	// The migration type of the migration to be performed.
	AssessmentMigrationType *string `json:"assessmentMigrationType,omitempty" tf:"assessment_migration_type,omitempty"`

	// Specifies the database objects to be excluded from the migration in bulk. The definition accepts input in a CSV format, newline separated for each entry. More details can be found in the documentation.
	BulkIncludeExcludeData *string `json:"bulkIncludeExcludeData,omitempty" tf:"bulk_include_exclude_data,omitempty"`

	// (Updatable) The OCID of the resource being referenced.
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// (Updatable) The type of assessment creation.
	CreationType *string `json:"creationType,omitempty" tf:"creation_type,omitempty"`

	// (Updatable) The combination of source and target databases participating in a migration. Example: ORACLE means the migration is meant for migrating Oracle source and target databases.
	DatabaseCombination *string `json:"databaseCombination,omitempty" tf:"database_combination,omitempty"`

	// (Updatable) The size of a source database.
	DatabaseDataSize *string `json:"databaseDataSize,omitempty" tf:"database_data_size,omitempty"`

	// (Updatable) DDL expectation values.
	DdlExpectation *string `json:"ddlExpectation,omitempty" tf:"ddl_expectation,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly description. Does not have to be unique, and it's changeable.  Avoid entering confidential information.
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable.  Avoid entering confidential information.
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Database objects to exclude from migration, cannot be specified alongside 'includeObjects'
	ExcludeObjects []ExcludeObjectsObservation `json:"excludeObjects,omitempty" tf:"exclude_objects,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.  For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// (Updatable) The OCID of the resource being referenced.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// Database objects to include from migration, cannot be specified alongside 'excludeObjects'
	IncludeObjects []IncludeObjectsObservation `json:"includeObjects,omitempty" tf:"include_objects,omitempty"`

	// True if CDB should be defined, false otherwise.
	IsCdbSupported *bool `json:"isCdbSupported,omitempty" tf:"is_cdb_supported,omitempty"`

	// The OCID of the resource being referenced.
	MigrationID *string `json:"migrationId,omitempty" tf:"migration_id,omitempty"`

	// (Updatable) A network speed in Megabits per second.
	NetworkSpeedMegabitPerSecond *string `json:"networkSpeedMegabitPerSecond,omitempty" tf:"network_speed_megabit_per_second,omitempty"`

	// (Updatable) Source Assessment Connection object
	SourceDatabaseConnection []SourceDatabaseConnectionObservation `json:"sourceDatabaseConnection,omitempty" tf:"source_database_connection,omitempty"`

	// The current state of the Assessment resource.
	State *string `json:"state,omitempty" tf:"state,omitempty"`

	// Usage of system tag keys. These predefined keys are scoped to namespaces. Example: {"orcl-cloud.free-tier-retained": "true"}
	// +mapType=granular
	SystemTags map[string]*string `json:"systemTags,omitempty" tf:"system_tags,omitempty"`

	// (Updatable) Target Assessment Connection object
	TargetDatabaseConnection []TargetDatabaseConnectionObservation `json:"targetDatabaseConnection,omitempty" tf:"target_database_connection,omitempty"`

	// An RFC3339 formatted datetime string such as 2016-08-25T21:10:29.600Z.
	TimeCreated *string `json:"timeCreated,omitempty" tf:"time_created,omitempty"`

	// An RFC3339 formatted datetime string such as 2016-08-25T21:10:29.600Z.
	TimeUpdated *string `json:"timeUpdated,omitempty" tf:"time_updated,omitempty"`
}

type MigrationAssessmentParameters struct {

	// (Updatable) Time allowed for the application downtime.
	// +kubebuilder:validation:Optional
	AcceptableDowntime *string `json:"acceptableDowntime,omitempty" tf:"acceptable_downtime,omitempty"`

	// Specifies the database objects to be excluded from the migration in bulk. The definition accepts input in a CSV format, newline separated for each entry. More details can be found in the documentation.
	// +kubebuilder:validation:Optional
	BulkIncludeExcludeData *string `json:"bulkIncludeExcludeData,omitempty" tf:"bulk_include_exclude_data,omitempty"`

	// (Updatable) The OCID of the resource being referenced.
	// +crossplane:generate:reference:type=github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1.Compartment
	// +kubebuilder:validation:Optional
	CompartmentID *string `json:"compartmentId,omitempty" tf:"compartment_id,omitempty"`

	// Reference to a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDRef *v1.NamespacedReference `json:"compartmentIdRef,omitempty" tf:"-"`

	// Selector for a Compartment in identity to populate compartmentId.
	// +kubebuilder:validation:Optional
	CompartmentIDSelector *v1.NamespacedSelector `json:"compartmentIdSelector,omitempty" tf:"-"`

	// (Updatable) The type of assessment creation.
	// +kubebuilder:validation:Optional
	CreationType *string `json:"creationType,omitempty" tf:"creation_type,omitempty"`

	// (Updatable) The combination of source and target databases participating in a migration. Example: ORACLE means the migration is meant for migrating Oracle source and target databases.
	// +kubebuilder:validation:Optional
	DatabaseCombination *string `json:"databaseCombination,omitempty" tf:"database_combination,omitempty"`

	// (Updatable) The size of a source database.
	// +kubebuilder:validation:Optional
	DatabaseDataSize *string `json:"databaseDataSize,omitempty" tf:"database_data_size,omitempty"`

	// (Updatable) DDL expectation values.
	// +kubebuilder:validation:Optional
	DdlExpectation *string `json:"ddlExpectation,omitempty" tf:"ddl_expectation,omitempty"`

	// (Updatable) Defined tags for this resource. Each key is predefined and scoped to a namespace. Example: {"foo-namespace.bar-key": "value"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	DefinedTags map[string]*string `json:"definedTags,omitempty" tf:"defined_tags,omitempty"`

	// (Updatable) A user-friendly description. Does not have to be unique, and it's changeable.  Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	Description *string `json:"description,omitempty" tf:"description,omitempty"`

	// (Updatable) A user-friendly name. Does not have to be unique, and it's changeable.  Avoid entering confidential information.
	// +kubebuilder:validation:Optional
	DisplayName *string `json:"displayName,omitempty" tf:"display_name,omitempty"`

	// Database objects to exclude from migration, cannot be specified alongside 'includeObjects'
	// +kubebuilder:validation:Optional
	ExcludeObjects []ExcludeObjectsParameters `json:"excludeObjects,omitempty" tf:"exclude_objects,omitempty"`

	// (Updatable) Free-form tags for this resource. Each tag is a simple key-value pair with no predefined name, type, or namespace.  For more information, see Resource Tags. Example: {"Department": "Finance"}
	// +kubebuilder:validation:Optional
	// +mapType=granular
	FreeformTags map[string]*string `json:"freeformTags,omitempty" tf:"freeform_tags,omitempty"`

	// Database objects to include from migration, cannot be specified alongside 'excludeObjects'
	// +kubebuilder:validation:Optional
	IncludeObjects []IncludeObjectsParameters `json:"includeObjects,omitempty" tf:"include_objects,omitempty"`

	// (Updatable) A network speed in Megabits per second.
	// +kubebuilder:validation:Optional
	NetworkSpeedMegabitPerSecond *string `json:"networkSpeedMegabitPerSecond,omitempty" tf:"network_speed_megabit_per_second,omitempty"`

	// (Updatable) Source Assessment Connection object
	// +kubebuilder:validation:Optional
	SourceDatabaseConnection []SourceDatabaseConnectionParameters `json:"sourceDatabaseConnection,omitempty" tf:"source_database_connection,omitempty"`

	// (Updatable) Target Assessment Connection object
	// +kubebuilder:validation:Optional
	TargetDatabaseConnection []TargetDatabaseConnectionParameters `json:"targetDatabaseConnection,omitempty" tf:"target_database_connection,omitempty"`
}

type SourceDatabaseConnectionInitParameters struct {

	// (Updatable) The OCID of the resource being referenced.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SourceDatabaseConnectionObservation struct {

	// (Updatable) The OCID of the resource being referenced.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`
}

type SourceDatabaseConnectionParameters struct {

	// (Updatable) The OCID of the resource being referenced.
	// +kubebuilder:validation:Optional
	ID *string `json:"id" tf:"id,omitempty"`
}

type TargetDatabaseConnectionInitParameters struct {

	// (Updatable) Defines the type of connection. For example, ORACLE.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (Updatable) The database version
	DatabaseVersion *string `json:"databaseVersion,omitempty" tf:"database_version,omitempty"`

	// (Updatable) The OCID of the resource being referenced.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Technology sub-type e.g. ADW_SHARED, ADW_DEDICATED, ATP_SHARED, ATP_DEDICATED
	TechnologySubType *string `json:"technologySubType,omitempty" tf:"technology_sub_type,omitempty"`

	// (Updatable) The technology type.
	TechnologyType *string `json:"technologyType,omitempty" tf:"technology_type,omitempty"`
}

type TargetDatabaseConnectionObservation struct {

	// (Updatable) Defines the type of connection. For example, ORACLE.
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (Updatable) The database version
	DatabaseVersion *string `json:"databaseVersion,omitempty" tf:"database_version,omitempty"`

	// (Updatable) The OCID of the resource being referenced.
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Technology sub-type e.g. ADW_SHARED, ADW_DEDICATED, ATP_SHARED, ATP_DEDICATED
	TechnologySubType *string `json:"technologySubType,omitempty" tf:"technology_sub_type,omitempty"`

	// (Updatable) The technology type.
	TechnologyType *string `json:"technologyType,omitempty" tf:"technology_type,omitempty"`
}

type TargetDatabaseConnectionParameters struct {

	// (Updatable) Defines the type of connection. For example, ORACLE.
	// +kubebuilder:validation:Optional
	ConnectionType *string `json:"connectionType,omitempty" tf:"connection_type,omitempty"`

	// (Updatable) The database version
	// +kubebuilder:validation:Optional
	DatabaseVersion *string `json:"databaseVersion,omitempty" tf:"database_version,omitempty"`

	// (Updatable) The OCID of the resource being referenced.
	// +kubebuilder:validation:Optional
	ID *string `json:"id,omitempty" tf:"id,omitempty"`

	// (Updatable) Technology sub-type e.g. ADW_SHARED, ADW_DEDICATED, ATP_SHARED, ATP_DEDICATED
	// +kubebuilder:validation:Optional
	TechnologySubType *string `json:"technologySubType,omitempty" tf:"technology_sub_type,omitempty"`

	// (Updatable) The technology type.
	// +kubebuilder:validation:Optional
	TechnologyType *string `json:"technologyType,omitempty" tf:"technology_type,omitempty"`
}

// MigrationAssessmentSpec defines the desired state of MigrationAssessment
type MigrationAssessmentSpec struct {
	v2.ManagedResourceSpec `json:",inline"`
	ForProvider            MigrationAssessmentParameters `json:"forProvider"`
	// THIS IS A BETA FIELD. It will be honored
	// unless the Management Policies feature flag is disabled.
	// InitProvider holds the same fields as ForProvider, with the exception
	// of Identifier and other resource reference fields. The fields that are
	// in InitProvider are merged into ForProvider when the resource is created.
	// The same fields are also added to the terraform ignore_changes hook, to
	// avoid updating them after creation. This is useful for fields that are
	// required on creation, but we do not desire to update them after creation,
	// for example because of an external controller is managing them, like an
	// autoscaler.
	InitProvider MigrationAssessmentInitParameters `json:"initProvider,omitempty"`
}

// MigrationAssessmentStatus defines the observed state of MigrationAssessment.
type MigrationAssessmentStatus struct {
	v1.ResourceStatus `json:",inline"`
	AtProvider        MigrationAssessmentObservation `json:"atProvider,omitempty"`
}

// +kubebuilder:object:root=true
// +kubebuilder:subresource:status
// +kubebuilder:storageversion

// MigrationAssessment is the Schema for the MigrationAssessments API. Provides the Assessment resource in Oracle Cloud Infrastructure Database Migration service
// +kubebuilder:printcolumn:name="SYNCED",type="string",JSONPath=".status.conditions[?(@.type=='Synced')].status"
// +kubebuilder:printcolumn:name="READY",type="string",JSONPath=".status.conditions[?(@.type=='Ready')].status"
// +kubebuilder:printcolumn:name="EXTERNAL-NAME",type="string",JSONPath=".metadata.annotations.crossplane\\.io/external-name"
// +kubebuilder:printcolumn:name="AGE",type="date",JSONPath=".metadata.creationTimestamp"
// +kubebuilder:resource:scope=Namespaced,categories={crossplane,managed,oci}
type MigrationAssessment struct {
	metav1.TypeMeta   `json:",inline"`
	metav1.ObjectMeta `json:"metadata,omitempty"`
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.acceptableDowntime) || (has(self.initProvider) && has(self.initProvider.acceptableDowntime))",message="spec.forProvider.acceptableDowntime is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.databaseCombination) || (has(self.initProvider) && has(self.initProvider.databaseCombination))",message="spec.forProvider.databaseCombination is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.databaseDataSize) || (has(self.initProvider) && has(self.initProvider.databaseDataSize))",message="spec.forProvider.databaseDataSize is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.ddlExpectation) || (has(self.initProvider) && has(self.initProvider.ddlExpectation))",message="spec.forProvider.ddlExpectation is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.networkSpeedMegabitPerSecond) || (has(self.initProvider) && has(self.initProvider.networkSpeedMegabitPerSecond))",message="spec.forProvider.networkSpeedMegabitPerSecond is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.sourceDatabaseConnection) || (has(self.initProvider) && has(self.initProvider.sourceDatabaseConnection))",message="spec.forProvider.sourceDatabaseConnection is a required parameter"
	// +kubebuilder:validation:XValidation:rule="!('*' in self.managementPolicies || 'Create' in self.managementPolicies || 'Update' in self.managementPolicies) || has(self.forProvider.targetDatabaseConnection) || (has(self.initProvider) && has(self.initProvider.targetDatabaseConnection))",message="spec.forProvider.targetDatabaseConnection is a required parameter"
	Spec   MigrationAssessmentSpec   `json:"spec"`
	Status MigrationAssessmentStatus `json:"status,omitempty"`
}

// +kubebuilder:object:root=true

// MigrationAssessmentList contains a list of MigrationAssessments
type MigrationAssessmentList struct {
	metav1.TypeMeta `json:",inline"`
	metav1.ListMeta `json:"metadata,omitempty"`
	Items           []MigrationAssessment `json:"items"`
}

// Repository type metadata.
var (
	MigrationAssessment_Kind             = "MigrationAssessment"
	MigrationAssessment_GroupKind        = schema.GroupKind{Group: CRDGroup, Kind: MigrationAssessment_Kind}.String()
	MigrationAssessment_KindAPIVersion   = MigrationAssessment_Kind + "." + CRDGroupVersion.String()
	MigrationAssessment_GroupVersionKind = CRDGroupVersion.WithKind(MigrationAssessment_Kind)
)

func init() {
	SchemeBuilder.Register(&MigrationAssessment{}, &MigrationAssessmentList{})
}
