---
apiVersion: logging.oci.m.upbound.io/v1alpha1
kind: LogGroup
metadata:
  labels:
    testing.upbound.io/example-name: loggroup_label_1
  name: loggroup1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: loggroup1
