---
apiVersion: logging.oci.m.upbound.io/v1alpha1
kind: UnifiedAgentConfiguration
metadata:
  labels:
    testing.upbound.io/example-name: unifiedagentconfiguration_label_1
  name: unifiedagentconfiguration1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    description: Unified Agent config
    displayName: unifiedagentconfiguration1
    isEnabled: true
    serviceConfiguration:
    - configurationType: LOGGING
      destination:
      - logObjectIdSelector:
          matchLabels:
            testing.upbound.io/example-name: log_label_2
      sources:
      - name: src1
        parser:
        - parserType: NONE
        paths:
        - /var/log/messages
        sourceType: LOG_TAIL
