---
apiVersion: artifacts.oci.m.upbound.io/v1alpha1
kind: ContainerImageSignature
metadata:
  labels:
    testing.upbound.io/example-name: containerimagesignature_label_1
  name: containerimagesignature1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    imageIdSelector:
      matchLabels:
        testing.upbound.io/example-name: image_label_1
    kmsKeyIdSelector:
      matchLabels:
        testing.upbound.io/example-name: key_label_1
    kmsKeyVersionIdSelector:
      matchLabels:
        testing.upbound.io/example-name: keyversion_label_1
    message: bWVzc2FnZQ==
    signature: ${VAULT_KEY_SIGNATURE}
    signingAlgorithm: SHA_256_RSA_PKCS1_V1_5
