/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha12 "github.com/oracle/provider-oci/apis/namespaced/database/v1alpha1"
	v1alpha1 "github.com/oracle/provider-oci/apis/namespaced/identity/v1alpha1"
	v1alpha11 "github.com/oracle/provider-oci/apis/namespaced/kms/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AccountRecoverySetting.
func (mg *AccountRecoverySetting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AccountRecoverySettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AccountRecoverySettingIDRef,
		Selector:     mg.Spec.ForProvider.AccountRecoverySettingIDSelector,
		To: reference.To{
			List:    &AccountRecoverySettingList{},
			Managed: &AccountRecoverySetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AccountRecoverySettingID")
	}
	mg.Spec.ForProvider.AccountRecoverySettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AccountRecoverySettingIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AccountRecoverySettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AccountRecoverySettingIDRef,
		Selector:     mg.Spec.InitProvider.AccountRecoverySettingIDSelector,
		To: reference.To{
			List:    &AccountRecoverySettingList{},
			Managed: &AccountRecoverySetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AccountRecoverySettingID")
	}
	mg.Spec.InitProvider.AccountRecoverySettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AccountRecoverySettingIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this ApiKey.
func (mg *ApiKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].OcidRef,
			Selector:     mg.Spec.ForProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Ocid")
		}
		mg.Spec.ForProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Value")
		}
		mg.Spec.ForProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].OcidRef,
			Selector:     mg.Spec.InitProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Ocid")
		}
		mg.Spec.InitProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Value")
		}
		mg.Spec.InitProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this AppRole.
func (mg *AppRole) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.App); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.App[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.App[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.App[i3].ValueSelector,
			To: reference.To{
				List:    &AppList{},
				Managed: &App{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.App[i3].Value")
		}
		mg.Spec.ForProvider.App[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.App[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.App); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.App[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.App[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.App[i3].ValueSelector,
			To: reference.To{
				List:    &AppList{},
				Managed: &App{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.App[i3].Value")
		}
		mg.Spec.InitProvider.App[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.App[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this AuthToken.
func (mg *AuthToken) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].OcidRef,
			Selector:     mg.Spec.ForProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Ocid")
		}
		mg.Spec.ForProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Value")
		}
		mg.Spec.ForProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].OcidRef,
			Selector:     mg.Spec.InitProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Ocid")
		}
		mg.Spec.InitProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Value")
		}
		mg.Spec.InitProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this AuthenticationFactorSetting.
func (mg *AuthenticationFactorSetting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AuthenticationFactorSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AuthenticationFactorSettingIDRef,
		Selector:     mg.Spec.ForProvider.AuthenticationFactorSettingIDSelector,
		To: reference.To{
			List:    &AuthenticationFactorSettingList{},
			Managed: &AuthenticationFactorSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AuthenticationFactorSettingID")
	}
	mg.Spec.ForProvider.AuthenticationFactorSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AuthenticationFactorSettingIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AuthenticationFactorSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AuthenticationFactorSettingIDRef,
		Selector:     mg.Spec.InitProvider.AuthenticationFactorSettingIDSelector,
		To: reference.To{
			List:    &AuthenticationFactorSettingList{},
			Managed: &AuthenticationFactorSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AuthenticationFactorSettingID")
	}
	mg.Spec.InitProvider.AuthenticationFactorSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AuthenticationFactorSettingIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this CloudGateMapping.
func (mg *CloudGateMapping) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.PolicyName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.PolicyNameRef,
		Selector:     mg.Spec.ForProvider.PolicyNameSelector,
		To: reference.To{
			List:    &v1alpha1.PolicyList{},
			Managed: &v1alpha1.Policy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.PolicyName")
	}
	mg.Spec.ForProvider.PolicyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.PolicyNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.PolicyName),
		Extract:      resource.ExtractParamPath("name", false),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.PolicyNameRef,
		Selector:     mg.Spec.InitProvider.PolicyNameSelector,
		To: reference.To{
			List:    &v1alpha1.PolicyList{},
			Managed: &v1alpha1.Policy{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.PolicyName")
	}
	mg.Spec.InitProvider.PolicyName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.PolicyNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this CustomerSecretKey.
func (mg *CustomerSecretKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].OcidRef,
			Selector:     mg.Spec.ForProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Ocid")
		}
		mg.Spec.ForProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Value")
		}
		mg.Spec.ForProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].OcidRef,
			Selector:     mg.Spec.InitProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Ocid")
		}
		mg.Spec.InitProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Value")
		}
		mg.Spec.InitProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this IdentityPropagationTrust.
func (mg *IdentityPropagationTrust) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ImpersonationServiceUsers); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ImpersonationServiceUsers[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ImpersonationServiceUsers[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.ImpersonationServiceUsers[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ImpersonationServiceUsers[i3].Value")
		}
		mg.Spec.ForProvider.ImpersonationServiceUsers[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ImpersonationServiceUsers[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.ImpersonationServiceUsers); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ImpersonationServiceUsers[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ImpersonationServiceUsers[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.ImpersonationServiceUsers[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ImpersonationServiceUsers[i3].Value")
		}
		mg.Spec.InitProvider.ImpersonationServiceUsers[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ImpersonationServiceUsers[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this IdentityProvider.
func (mg *IdentityProvider) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyIDRef,
			Selector:     mg.Spec.ForProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyIDSelector,
			To: reference.To{
				List:    &v1alpha11.KeyList{},
				Managed: &v1alpha11.Key{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyID")
		}
		mg.Spec.ForProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyIDRef,
			Selector:     mg.Spec.InitProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyIDSelector,
			To: reference.To{
				List:    &v1alpha11.KeyList{},
				Managed: &v1alpha11.Key{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyID")
		}
		mg.Spec.InitProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.UrnietfparamsscimschemasoracleidcsextensionsocialIdentityProvider[i3].AppleKeyIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this IdentitySetting.
func (mg *IdentitySetting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IdentitySettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.IdentitySettingIDRef,
		Selector:     mg.Spec.ForProvider.IdentitySettingIDSelector,
		To: reference.To{
			List:    &IdentitySettingList{},
			Managed: &IdentitySetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IdentitySettingID")
	}
	mg.Spec.ForProvider.IdentitySettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IdentitySettingIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IdentitySettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.IdentitySettingIDRef,
		Selector:     mg.Spec.InitProvider.IdentitySettingIDSelector,
		To: reference.To{
			List:    &IdentitySettingList{},
			Managed: &IdentitySetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.IdentitySettingID")
	}
	mg.Spec.InitProvider.IdentitySettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IdentitySettingIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this KmsiSetting.
func (mg *KmsiSetting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KmsiSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KmsiSettingIDRef,
		Selector:     mg.Spec.ForProvider.KmsiSettingIDSelector,
		To: reference.To{
			List:    &KmsiSettingList{},
			Managed: &KmsiSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KmsiSettingID")
	}
	mg.Spec.ForProvider.KmsiSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KmsiSettingIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KmsiSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KmsiSettingIDRef,
		Selector:     mg.Spec.InitProvider.KmsiSettingIDSelector,
		To: reference.To{
			List:    &KmsiSettingList{},
			Managed: &KmsiSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KmsiSettingID")
	}
	mg.Spec.InitProvider.KmsiSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KmsiSettingIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MappedAttribute.
func (mg *MappedAttribute) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MappedAttributeID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MappedAttributeIDRef,
		Selector:     mg.Spec.ForProvider.MappedAttributeIDSelector,
		To: reference.To{
			List:    &MappedAttributeList{},
			Managed: &MappedAttribute{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MappedAttributeID")
	}
	mg.Spec.ForProvider.MappedAttributeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MappedAttributeIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MappedAttributeID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MappedAttributeIDRef,
		Selector:     mg.Spec.InitProvider.MappedAttributeIDSelector,
		To: reference.To{
			List:    &MappedAttributeList{},
			Managed: &MappedAttribute{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MappedAttributeID")
	}
	mg.Spec.InitProvider.MappedAttributeID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MappedAttributeIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this MyRequest.
func (mg *MyRequest) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Requesting); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Requesting[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Requesting[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.Requesting[i3].ValueSelector,
			To: reference.To{
				List:    &GroupList{},
				Managed: &Group{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Requesting[i3].Value")
		}
		mg.Spec.ForProvider.Requesting[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Requesting[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Requesting); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Requesting[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Requesting[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.Requesting[i3].ValueSelector,
			To: reference.To{
				List:    &GroupList{},
				Managed: &Group{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Requesting[i3].Value")
		}
		mg.Spec.InitProvider.Requesting[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Requesting[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this NotificationSetting.
func (mg *NotificationSetting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.NotificationSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.NotificationSettingIDRef,
		Selector:     mg.Spec.ForProvider.NotificationSettingIDSelector,
		To: reference.To{
			List:    &NotificationSettingList{},
			Managed: &NotificationSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.NotificationSettingID")
	}
	mg.Spec.ForProvider.NotificationSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.NotificationSettingIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.NotificationSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.NotificationSettingIDRef,
		Selector:     mg.Spec.InitProvider.NotificationSettingIDSelector,
		To: reference.To{
			List:    &NotificationSettingList{},
			Managed: &NotificationSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.NotificationSettingID")
	}
	mg.Spec.InitProvider.NotificationSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.NotificationSettingIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this Oauth2clientCredential.
func (mg *Oauth2clientCredential) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].OcidRef,
			Selector:     mg.Spec.ForProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Ocid")
		}
		mg.Spec.ForProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Value")
		}
		mg.Spec.ForProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].OcidRef,
			Selector:     mg.Spec.InitProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Ocid")
		}
		mg.Spec.InitProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Value")
		}
		mg.Spec.InitProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this OauthPartnerCertificate.
func (mg *OauthPartnerCertificate) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KeyStoreID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KeyStoreIDRef,
		Selector:     mg.Spec.ForProvider.KeyStoreIDSelector,
		To: reference.To{
			List:    &v1alpha12.KeyStoreList{},
			Managed: &v1alpha12.KeyStore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KeyStoreID")
	}
	mg.Spec.ForProvider.KeyStoreID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KeyStoreIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KeyStoreName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.KeyStoreNameRef,
		Selector:     mg.Spec.ForProvider.KeyStoreNameSelector,
		To: reference.To{
			List:    &v1alpha12.KeyStoreList{},
			Managed: &v1alpha12.KeyStore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.KeyStoreName")
	}
	mg.Spec.ForProvider.KeyStoreName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.KeyStoreNameRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KeyStoreID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KeyStoreIDRef,
		Selector:     mg.Spec.InitProvider.KeyStoreIDSelector,
		To: reference.To{
			List:    &v1alpha12.KeyStoreList{},
			Managed: &v1alpha12.KeyStore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KeyStoreID")
	}
	mg.Spec.InitProvider.KeyStoreID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KeyStoreIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KeyStoreName),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.KeyStoreNameRef,
		Selector:     mg.Spec.InitProvider.KeyStoreNameSelector,
		To: reference.To{
			List:    &v1alpha12.KeyStoreList{},
			Managed: &v1alpha12.KeyStore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.KeyStoreName")
	}
	mg.Spec.InitProvider.KeyStoreName = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.KeyStoreNameRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this PasswordPolicy.
func (mg *PasswordPolicy) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.Groups); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.Groups[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.Groups[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.Groups[i3].ValueSelector,
			To: reference.To{
				List:    &GroupList{},
				Managed: &Group{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.Groups[i3].Value")
		}
		mg.Spec.ForProvider.Groups[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.Groups[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.Groups); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.Groups[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.Groups[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.Groups[i3].ValueSelector,
			To: reference.To{
				List:    &GroupList{},
				Managed: &Group{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.Groups[i3].Value")
		}
		mg.Spec.InitProvider.Groups[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.Groups[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this SecurityQuestionSetting.
func (mg *SecurityQuestionSetting) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.SecurityQuestionSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.SecurityQuestionSettingIDRef,
		Selector:     mg.Spec.ForProvider.SecurityQuestionSettingIDSelector,
		To: reference.To{
			List:    &SecurityQuestionSettingList{},
			Managed: &SecurityQuestionSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.SecurityQuestionSettingID")
	}
	mg.Spec.ForProvider.SecurityQuestionSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.SecurityQuestionSettingIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.SecurityQuestionSettingID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.SecurityQuestionSettingIDRef,
		Selector:     mg.Spec.InitProvider.SecurityQuestionSettingIDSelector,
		To: reference.To{
			List:    &SecurityQuestionSettingList{},
			Managed: &SecurityQuestionSetting{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.SecurityQuestionSettingID")
	}
	mg.Spec.InitProvider.SecurityQuestionSettingID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.SecurityQuestionSettingIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this SmtpCredential.
func (mg *SmtpCredential) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].OcidRef,
			Selector:     mg.Spec.ForProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Ocid")
		}
		mg.Spec.ForProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Value")
		}
		mg.Spec.ForProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].OcidRef,
			Selector:     mg.Spec.InitProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Ocid")
		}
		mg.Spec.InitProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Value")
		}
		mg.Spec.InitProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this SocialIdentityProvider.
func (mg *SocialIdentityProvider) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.AppleKeyID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.AppleKeyIDRef,
		Selector:     mg.Spec.ForProvider.AppleKeyIDSelector,
		To: reference.To{
			List:    &v1alpha11.KeyList{},
			Managed: &v1alpha11.Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.AppleKeyID")
	}
	mg.Spec.ForProvider.AppleKeyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.AppleKeyIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.AppleKeyID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.AppleKeyIDRef,
		Selector:     mg.Spec.InitProvider.AppleKeyIDSelector,
		To: reference.To{
			List:    &v1alpha11.KeyList{},
			Managed: &v1alpha11.Key{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.AppleKeyID")
	}
	mg.Spec.InitProvider.AppleKeyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.AppleKeyIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this UserDbCredential.
func (mg *UserDbCredential) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPINamespacedResolver(c, mg)

	var rsp reference.NamespacedResolutionResponse
	var err error

	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].OcidRef,
			Selector:     mg.Spec.ForProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Ocid")
		}
		mg.Spec.ForProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.User[i3].ValueRef,
			Selector:     mg.Spec.ForProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.User[i3].Value")
		}
		mg.Spec.ForProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.User[i3].ValueRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Ocid),
			Extract:      resource.ExtractParamPath("ocid", false),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].OcidRef,
			Selector:     mg.Spec.InitProvider.User[i3].OcidSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Ocid")
		}
		mg.Spec.InitProvider.User[i3].Ocid = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].OcidRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.User); i3++ {
		rsp, err = r.Resolve(ctx, reference.NamespacedResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.User[i3].Value),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.User[i3].ValueRef,
			Selector:     mg.Spec.InitProvider.User[i3].ValueSelector,
			To: reference.To{
				List:    &UserList{},
				Managed: &User{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.User[i3].Value")
		}
		mg.Spec.InitProvider.User[i3].Value = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.User[i3].ValueRef = rsp.ResolvedReference

	}

	return nil
}
