---
apiVersion: events.oci.m.upbound.io/v1alpha1
kind: Rule
metadata:
  labels:
    testing.upbound.io/example-name: rule_label_1
  name: rule1
  namespace: crossplane-system
spec:
  forProvider:
    actions:
    - actions:
      - actionType: FAAS
        description: invoke function
        functionIdSelector:
          matchLabels:
            testing.upbound.io/example-name: function_label_1
        isEnabled: true
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    condition: '{}'
    displayName: rule1
    isEnabled: true
