---
apiVersion: filestorage.oci.m.upbound.io/v1alpha1
kind: MountTarget
metadata:
  labels:
    testing.upbound.io/example-name: mounttarget_label_1
  name: mounttarget1
  namespace: crossplane-system
spec:
  forProvider:
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: ~
    subnetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: subnet_label_1
