---
apiVersion: filestorage.oci.m.upbound.io/v1alpha1
kind: OutboundConnector
metadata:
  labels:
    testing.upbound.io/example-name: outboundconnector_label_1
  name: outboundconnector1
  namespace: crossplane-system
spec:
  forProvider:
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    bindDistinguishedName: cn=binduser,dc=example,dc=com
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    connectorType: LDAPBIND
    displayName: outboundconnector1
    endpoints:
    - hostname: ldap.example.com
      port: '636'
    passwordSecretIdSelector:
      matchLabels:
        testing.upbound.io/example-name: secret_label_1
    passwordSecretVersion: 1
