---
apiVersion: filestorage.oci.m.upbound.io/v1alpha1
kind: Replication
metadata:
  labels:
    testing.upbound.io/example-name: replication_label_1
  name: replication1
  namespace: crossplane-system
spec:
  forProvider:
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: replication1
    sourceIdSelector:
      matchLabels:
        testing.upbound.io/example-name: filesystem_label_1
    targetIdSelector:
      matchLabels:
        testing.upbound.io/example-name: filesystem_label_2
