---
apiVersion: filestorage.oci.m.upbound.io/v1alpha1
kind: Snapshot
metadata:
  labels:
    testing.upbound.io/example-name: snapshot_label_1
  name: snapshot1
  namespace: crossplane-system
spec:
  forProvider:
    fileSystemIdSelector:
      matchLabels:
        testing.upbound.io/example-name: filesystem_label_1
    name: snapshot1
