---
apiVersion: filestorage.oci.m.upbound.io/v1alpha1
kind: FileSystem
metadata:
  labels:
    testing.upbound.io/example-name: filesystem_label_1
  name: filesystem1
  namespace: crossplane-system
spec:
  forProvider:
    availabilityDomain: ${AVAILABILITY_DOMAIN}
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    displayName: filesystem1
