---
apiVersion: certificatesmanagement.oci.m.upbound.io/v1alpha1
kind: Certificate
metadata:
  labels:
    testing.upbound.io/example-name: certificate_label_1
  name: certificate1
  namespace: crossplane-system
spec:
  forProvider:
    certificateConfig:
    - certificateProfileType: TLS_SERVER_OR_CLIENT_AUTH
      configType: ISSUED_BY_INTERNAL_CA
      issuerCertificateAuthorityIdSelector:
        matchLabels:
          testing.upbound.io/example-name: certificateauthority_label_1
      subject:
      - commonName: example.oracle.com
    compartmentIdSelector:
      matchLabels:
        testing.upbound.io/example-name: compartment_label_1
    name: certificate1
