/*
Copyright 2022 Upbound Inc.
*/
// Code generated by angryjet. DO NOT EDIT.

package v1alpha1

import (
	"context"
	reference "github.com/crossplane/crossplane-runtime/v2/pkg/reference"
	resource "github.com/crossplane/upjet/v2/pkg/resource"
	v1alpha14 "github.com/oracle/provider-oci/apis/cluster/datacatalog/v1alpha1"
	v1alpha12 "github.com/oracle/provider-oci/apis/cluster/dataflow/v1alpha1"
	v1alpha1 "github.com/oracle/provider-oci/apis/cluster/identity/v1alpha1"
	v1alpha13 "github.com/oracle/provider-oci/apis/cluster/kms/v1alpha1"
	v1alpha11 "github.com/oracle/provider-oci/apis/cluster/networking/v1alpha1"
	errors "github.com/pkg/errors"
	client "sigs.k8s.io/controller-runtime/pkg/client"
)

// ResolveReferences of this AutoScalingConfiguration.
func (mg *AutoScalingConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsCapacityReport.
func (mg *BdsCapacityReport) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstance.
func (mg *BdsInstance) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.CompartmentIDRef,
		Selector:     mg.Spec.ForProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.CompartmentID")
	}
	mg.Spec.ForProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.ComputeOnlyWorkerNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ComputeOnlyWorkerNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.ComputeOnlyWorkerNode[i3].SubnetIDRef,
			Selector:     mg.Spec.ForProvider.ComputeOnlyWorkerNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.ComputeOnlyWorkerNode[i3].SubnetID")
		}
		mg.Spec.ForProvider.ComputeOnlyWorkerNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.ComputeOnlyWorkerNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.EdgeNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.EdgeNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.EdgeNode[i3].SubnetIDRef,
			Selector:     mg.Spec.ForProvider.EdgeNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.EdgeNode[i3].SubnetID")
		}
		mg.Spec.ForProvider.EdgeNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.EdgeNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.KafkaBrokerNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.KafkaBrokerNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.KafkaBrokerNode[i3].SubnetIDRef,
			Selector:     mg.Spec.ForProvider.KafkaBrokerNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.KafkaBrokerNode[i3].SubnetID")
		}
		mg.Spec.ForProvider.KafkaBrokerNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.KafkaBrokerNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.MasterNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MasterNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.MasterNode[i3].SubnetIDRef,
			Selector:     mg.Spec.ForProvider.MasterNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.MasterNode[i3].SubnetID")
		}
		mg.Spec.ForProvider.MasterNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.MasterNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.UtilNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UtilNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.UtilNode[i3].SubnetIDRef,
			Selector:     mg.Spec.ForProvider.UtilNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.UtilNode[i3].SubnetID")
		}
		mg.Spec.ForProvider.UtilNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.UtilNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.WorkerNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.WorkerNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.WorkerNode[i3].SubnetIDRef,
			Selector:     mg.Spec.ForProvider.WorkerNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.WorkerNode[i3].SubnetID")
		}
		mg.Spec.ForProvider.WorkerNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.WorkerNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.CompartmentID),
		Extract:      reference.ExternalName(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.CompartmentIDRef,
		Selector:     mg.Spec.InitProvider.CompartmentIDSelector,
		To: reference.To{
			List:    &v1alpha1.CompartmentList{},
			Managed: &v1alpha1.Compartment{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.CompartmentID")
	}
	mg.Spec.InitProvider.CompartmentID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.CompartmentIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.ComputeOnlyWorkerNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ComputeOnlyWorkerNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.ComputeOnlyWorkerNode[i3].SubnetIDRef,
			Selector:     mg.Spec.InitProvider.ComputeOnlyWorkerNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.ComputeOnlyWorkerNode[i3].SubnetID")
		}
		mg.Spec.InitProvider.ComputeOnlyWorkerNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.ComputeOnlyWorkerNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.EdgeNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.EdgeNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.EdgeNode[i3].SubnetIDRef,
			Selector:     mg.Spec.InitProvider.EdgeNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.EdgeNode[i3].SubnetID")
		}
		mg.Spec.InitProvider.EdgeNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.EdgeNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.KafkaBrokerNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.KafkaBrokerNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.KafkaBrokerNode[i3].SubnetIDRef,
			Selector:     mg.Spec.InitProvider.KafkaBrokerNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.KafkaBrokerNode[i3].SubnetID")
		}
		mg.Spec.InitProvider.KafkaBrokerNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.KafkaBrokerNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.MasterNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MasterNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.MasterNode[i3].SubnetIDRef,
			Selector:     mg.Spec.InitProvider.MasterNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.MasterNode[i3].SubnetID")
		}
		mg.Spec.InitProvider.MasterNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.MasterNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.UtilNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UtilNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.UtilNode[i3].SubnetIDRef,
			Selector:     mg.Spec.InitProvider.UtilNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.UtilNode[i3].SubnetID")
		}
		mg.Spec.InitProvider.UtilNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.UtilNode[i3].SubnetIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.WorkerNode); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.WorkerNode[i3].SubnetID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.WorkerNode[i3].SubnetIDRef,
			Selector:     mg.Spec.InitProvider.WorkerNode[i3].SubnetIDSelector,
			To: reference.To{
				List:    &v1alpha11.SubnetList{},
				Managed: &v1alpha11.Subnet{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.WorkerNode[i3].SubnetID")
		}
		mg.Spec.InitProvider.WorkerNode[i3].SubnetID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.WorkerNode[i3].SubnetIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this BdsInstanceApiKey.
func (mg *BdsInstanceApiKey) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UserID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.UserIDRef,
		Selector:     mg.Spec.ForProvider.UserIDSelector,
		To: reference.To{
			List:    &v1alpha1.UserList{},
			Managed: &v1alpha1.User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.UserID")
	}
	mg.Spec.ForProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.UserIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UserID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.UserIDRef,
		Selector:     mg.Spec.InitProvider.UserIDSelector,
		To: reference.To{
			List:    &v1alpha1.UserList{},
			Managed: &v1alpha1.User{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.UserID")
	}
	mg.Spec.InitProvider.UserID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.UserIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceIdentityConfiguration.
func (mg *BdsInstanceIdentityConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.ConfidentialApplicationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.ConfidentialApplicationIDRef,
		Selector:     mg.Spec.ForProvider.ConfidentialApplicationIDSelector,
		To: reference.To{
			List:    &v1alpha12.ApplicationList{},
			Managed: &v1alpha12.Application{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.ConfidentialApplicationID")
	}
	mg.Spec.ForProvider.ConfidentialApplicationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.ConfidentialApplicationIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.IdentityDomainID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.IdentityDomainIDRef,
		Selector:     mg.Spec.ForProvider.IdentityDomainIDSelector,
		To: reference.To{
			List:    &v1alpha1.DomainList{},
			Managed: &v1alpha1.Domain{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.IdentityDomainID")
	}
	mg.Spec.ForProvider.IdentityDomainID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.IdentityDomainIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.ForProvider.UpstConfigurationDetails); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyIDRef,
			Selector:     mg.Spec.ForProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyIDSelector,
			To: reference.To{
				List:    &v1alpha13.KeyList{},
				Managed: &v1alpha13.Key{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyID")
		}
		mg.Spec.ForProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.ForProvider.UpstConfigurationDetails); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.UpstConfigurationDetails[i3].VaultID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.ForProvider.UpstConfigurationDetails[i3].VaultIDRef,
			Selector:     mg.Spec.ForProvider.UpstConfigurationDetails[i3].VaultIDSelector,
			To: reference.To{
				List:    &v1alpha13.VaultList{},
				Managed: &v1alpha13.Vault{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.ForProvider.UpstConfigurationDetails[i3].VaultID")
		}
		mg.Spec.ForProvider.UpstConfigurationDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.ForProvider.UpstConfigurationDetails[i3].VaultIDRef = rsp.ResolvedReference

	}
	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.ConfidentialApplicationID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.ConfidentialApplicationIDRef,
		Selector:     mg.Spec.InitProvider.ConfidentialApplicationIDSelector,
		To: reference.To{
			List:    &v1alpha12.ApplicationList{},
			Managed: &v1alpha12.Application{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.ConfidentialApplicationID")
	}
	mg.Spec.InitProvider.ConfidentialApplicationID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.ConfidentialApplicationIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.IdentityDomainID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.IdentityDomainIDRef,
		Selector:     mg.Spec.InitProvider.IdentityDomainIDSelector,
		To: reference.To{
			List:    &v1alpha1.DomainList{},
			Managed: &v1alpha1.Domain{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.IdentityDomainID")
	}
	mg.Spec.InitProvider.IdentityDomainID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.IdentityDomainIDRef = rsp.ResolvedReference

	for i3 := 0; i3 < len(mg.Spec.InitProvider.UpstConfigurationDetails); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyIDRef,
			Selector:     mg.Spec.InitProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyIDSelector,
			To: reference.To{
				List:    &v1alpha13.KeyList{},
				Managed: &v1alpha13.Key{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyID")
		}
		mg.Spec.InitProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.UpstConfigurationDetails[i3].MasterEncryptionKeyIDRef = rsp.ResolvedReference

	}
	for i3 := 0; i3 < len(mg.Spec.InitProvider.UpstConfigurationDetails); i3++ {
		rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
			CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.UpstConfigurationDetails[i3].VaultID),
			Extract:      resource.ExtractResourceID(),
			Namespace:    mg.GetNamespace(),
			Reference:    mg.Spec.InitProvider.UpstConfigurationDetails[i3].VaultIDRef,
			Selector:     mg.Spec.InitProvider.UpstConfigurationDetails[i3].VaultIDSelector,
			To: reference.To{
				List:    &v1alpha13.VaultList{},
				Managed: &v1alpha13.Vault{},
			},
		})
		if err != nil {
			return errors.Wrap(err, "mg.Spec.InitProvider.UpstConfigurationDetails[i3].VaultID")
		}
		mg.Spec.InitProvider.UpstConfigurationDetails[i3].VaultID = reference.ToPtrValue(rsp.ResolvedValue)
		mg.Spec.InitProvider.UpstConfigurationDetails[i3].VaultIDRef = rsp.ResolvedReference

	}

	return nil
}

// ResolveReferences of this BdsInstanceMetastoreConfig.
func (mg *BdsInstanceMetastoreConfig) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsAPIKeyID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsAPIKeyIDRef,
		Selector:     mg.Spec.ForProvider.BdsAPIKeyIDSelector,
		To: reference.To{
			List:    &v1alpha1.ApiKeyList{},
			Managed: &v1alpha1.ApiKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsAPIKeyID")
	}
	mg.Spec.ForProvider.BdsAPIKeyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsAPIKeyIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.MetastoreID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.MetastoreIDRef,
		Selector:     mg.Spec.ForProvider.MetastoreIDSelector,
		To: reference.To{
			List:    &v1alpha14.MetastoreList{},
			Managed: &v1alpha14.Metastore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.MetastoreID")
	}
	mg.Spec.ForProvider.MetastoreID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.MetastoreIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsAPIKeyID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsAPIKeyIDRef,
		Selector:     mg.Spec.InitProvider.BdsAPIKeyIDSelector,
		To: reference.To{
			List:    &v1alpha1.ApiKeyList{},
			Managed: &v1alpha1.ApiKey{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsAPIKeyID")
	}
	mg.Spec.InitProvider.BdsAPIKeyID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsAPIKeyIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.MetastoreID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.MetastoreIDRef,
		Selector:     mg.Spec.InitProvider.MetastoreIDSelector,
		To: reference.To{
			List:    &v1alpha14.MetastoreList{},
			Managed: &v1alpha14.Metastore{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.MetastoreID")
	}
	mg.Spec.InitProvider.MetastoreID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.MetastoreIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceNodeBackup.
func (mg *BdsInstanceNodeBackup) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceNodeBackupConfiguration.
func (mg *BdsInstanceNodeBackupConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceNodeReplaceConfiguration.
func (mg *BdsInstanceNodeReplaceConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceOperationCertificateManagementsManagement.
func (mg *BdsInstanceOperationCertificateManagementsManagement) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceOsPatchAction.
func (mg *BdsInstanceOsPatchAction) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstancePatchAction.
func (mg *BdsInstancePatchAction) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceReplaceNodeAction.
func (mg *BdsInstanceReplaceNodeAction) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceResourcePrincipalConfiguration.
func (mg *BdsInstanceResourcePrincipalConfiguration) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}

// ResolveReferences of this BdsInstanceSoftwareUpdateAction.
func (mg *BdsInstanceSoftwareUpdateAction) ResolveReferences(ctx context.Context, c client.Reader) error {
	r := reference.NewAPIResolver(c, mg)

	var rsp reference.ResolutionResponse
	var err error

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.ForProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.ForProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.ForProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.ForProvider.BdsInstanceID")
	}
	mg.Spec.ForProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.ForProvider.BdsInstanceIDRef = rsp.ResolvedReference

	rsp, err = r.Resolve(ctx, reference.ResolutionRequest{
		CurrentValue: reference.FromPtrValue(mg.Spec.InitProvider.BdsInstanceID),
		Extract:      resource.ExtractResourceID(),
		Namespace:    mg.GetNamespace(),
		Reference:    mg.Spec.InitProvider.BdsInstanceIDRef,
		Selector:     mg.Spec.InitProvider.BdsInstanceIDSelector,
		To: reference.To{
			List:    &BdsInstanceList{},
			Managed: &BdsInstance{},
		},
	})
	if err != nil {
		return errors.Wrap(err, "mg.Spec.InitProvider.BdsInstanceID")
	}
	mg.Spec.InitProvider.BdsInstanceID = reference.ToPtrValue(rsp.ResolvedValue)
	mg.Spec.InitProvider.BdsInstanceIDRef = rsp.ResolvedReference

	return nil
}
