apiVersion: database.oci.upbound.io/v1alpha1
kind: DataPatch
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/datapatch
  labels:
    testing.upbound.io/example-name: example
  name: example
spec:
  forProvider:
    action: APPLY
    dataPatchOptions:
    - shouldSkipClosedPdbs: true
    databaseIdSelector:
      matchLabels:
        testing.upbound.io/example-name: example
    pluggableDatabasesRefs:
    - name: example
