apiVersion: database.oci.upbound.io/v1alpha1
kind: ManagementCloudExadataStorageGrid
metadata:
  annotations:
    meta.upbound.io/example-id: database/v1alpha1/managementcloudexadatastoragegrid
  labels:
    testing.upbound.io/example-name: test_cloud_exadata_storage_grid
  name: test-cloud-exadata-storage-grid
spec:
  forProvider:
    cloudExadataStorageGridIdSelector:
      matchLabels:
        testing.upbound.io/example-name: test_cloud_exadata_storage_grid
    definedTags:
      Operations.CostCenter: "42"
    freeformTags:
      Department: Finance
