---
apiVersion: monitoring.oci.m.upbound.io/v1alpha1
kind: AlarmSuppression
metadata:
  labels:
    testing.upbound.io/example-name: alarmsuppression_label_1
  name: alarmsuppression1
  namespace: crossplane-system
spec:
  forProvider:
    alarmSuppressionTarget:
    - alarmIdSelector:
        matchLabels:
          testing.upbound.io/example-name: alarm_label_1
      targetType: ALARM
    dimensions:
      availabilityDomain: phx-ad-1
    displayName: alarmsuppression1
    timeSuppressFrom: 2026-02-22T20:43:40Z
    timeSuppressUntil: 2026-02-22T20:53:30Z
